### ISSUE TITLE
Revamping the footer section

### ISSUE THREAD

**Issue by Sakshi0401** [Girl-Code-It/Opportunity-Calendar-Frontend#100]
**Footer section** is vague as compare to other part of website. As a **GSSOC'21** participant I would like to work on this section.

![image](https://user-images.githubusercontent.com/64726139/111028175-0652b880-841b-11eb-844c-05315b807f8f.png)

**Comment by abdus** [comment]
Please explain the changes you are going to make in details. 

cc @vaishali614 @Surajbokde

**Comment by DeepanshiD** [comment]
@Sakshi0401 
You have to make something like this, in case of any queries feel free to ping
![WhatsApp Image 2021-03-14 at 10 56 56](https://user-images.githubusercontent.com/41962533/111058352-14084c80-84b4-11eb-9009-7c2eecf1b714.jpeg)

**Comment by rajesh6161** [comment]
I have a more intuitive idea about the footer section
![GSOC](https://user-images.githubusercontent.com/40054161/111072802-35902500-8502-11eb-962e-a37de7581a8c.jpg)

**Comment by Sakshi0401** [comment]
@DeepanshiD So shall I start working on this? Please assign the issue

**Comment by DeepanshiD** [comment]
@Sakshi0401 , @rajesh6161 the above design is fair. You can keep Products and Links above line and in blue color.And Contact us also in blue
Besides, we assign tasks on First Come First Serve bases, so @Sakshi0401 has to start with it

**Comment by Sakshi0401** [comment]
@DeepanshiD which design should I refer?

**Comment by DeepanshiD** [comment]
@Sakshi0401 Go with second one with mentioned changes

**Comment by Sakshi0401** [comment]
@DeepanshiD Okay Thanks

**Comment by rajesh6161** [comment]
Okay @DeepanshiD I will look into it. Best of luck @Sakshi0401

**Comment by Sakshi0401** [comment]
Hey @DeepanshiD I have made all necessary changes. Please consider reviewing. Also could you please label this issue as GSSoC'21. Thank you!

![image](https://user-images.githubusercontent.com/64726139/111201186-88440c80-85e8-11eb-9a1d-72fcc462a23e.png)

**Comment by DeepanshiD** [comment]
Hey @Sakshi0401 Great work! @abdus you can mark it as GSSOC'21 and close it ig, its great to go

**Comment by rajesh6161** [comment]
Awesome @Sakshi0401 🙌 Good but try putting that blue line under PRODUCTS and LINKS plus move the logos up a bit and add spacing between contact us and logo and its perfect. right @DeepanshiD

**Comment by DeepanshiD** [comment]
@rajesh6161 We will come up with complete revamp for the whole product, then we will look into the intricate of design, for now this seems fine, but yes @Sakshi0401 you can increase vertical spacing between Products and Codemaps and Links and TnC. And it will be great if you keep blue line under Links and Products rather than keeping them at bottom. 
Thanks @rajesh6161 for suggestions!

**Comment by Sakshi0401** [comment]
@rajesh6161 Thanks for suggestions! @DeepanshiD I'll do these changes.

**Comment by Sakshi0401** [comment]
> @rajesh6161 We will come up with complete revamp for the whole product, then we will look into the intricate of design, for now this seems fine, but yes @Sakshi0401 you can increase vertical spacing between Products and Codemaps and Links and TnC. And it will be great if you keep blue line under Links and Products rather than keeping them at bottom.
> Thanks @rajesh6161 for suggestions!

@DeepanshiD I am done with these changes. Now I am making footer responsive for other devices. I'll come back to you soon.

**Comment by DeepanshiD** [comment]
@Sakshi0401 Great!

**Comment by Sakshi0401** [comment]
@DeepanshiD Made all the necessary changes #114 Please consider. Thank you !!
