### ISSUE TITLE
On clicking Post opportunity form not comes

### ISSUE THREAD

**Issue by saumyasrivastava08** [Girl-Code-It/Opportunity-Calendar-Frontend#103]
![Screenshot (64)](https://user-images.githubusercontent.com/57553757/111062122-07442280-84cd-11eb-8615-fe04f0983798.png)

On clicking Hackathons and schlorships post opportunity form not comes .

Can I take this issue

**Comment by saumyasrivastava08** [comment]
@abdus @Surajbokde can i work on this?

**Comment by abdus** [comment]
https://user-images.githubusercontent.com/32123917/111075383-d1735e00-850d-11eb-9cff-bd7afff364cc.mp4

it works.

**Comment by Manvityagi** [comment]
Closing this issue as @abdus pointed out it works.
