### ISSUE TITLE
Adding a background carousel

### ISSUE THREAD

**Issue by drishtipeshwani** [Girl-Code-It/Opportunity-Calendar-Frontend#106]
Hello ! I am a GSSOC Participant 
Here rather than having a purple background can we have a background carousel with images and post opportunity button over it, I think it will look nice. Do assign me this issue Thank you
<img width="941" alt="2021-03-14" src="https://user-images.githubusercontent.com/65016769/111069106-8cd9c980-84f1-11eb-84a4-75f5c8e27c37.png">

**Comment by ShambhaviSharma0110** [comment]
Hey! I would really like to work on this please allow me to work on this...
-gssoc'21 participant

**Comment by Manvityagi** [comment]
Sounds good @drishtipeshwani. Give it a try. 
Would love to see what you come up with.

**Comment by Manvityagi** [comment]
@DeepanshiD is our Design Mentor. 
You can get in touch with her for discussions. 

CC: @DeepanshiD, @drishtipeshwani

**Comment by drishtipeshwani** [comment]
Yeah, Sure Thank you

**Comment by drishtipeshwani** [comment]
@DeepanshiD  Hey!! Like I have added a three image carousel I just wanted to get it verified before making a pull request. Like should I even style the button any suggestions from your side any changes you would suggest?

https://user-images.githubusercontent.com/65016769/111916666-0188a700-8aa2-11eb-92c2-d84718e1078c.mp4

**Comment by vaishali614** [comment]
> @DeepanshiD Hey!! Like I have added a three image carousel I just wanted to get it verified before making a pull request. Like should I even style the button any suggestions from your side any changes you would suggest?
> 
>  girl-code-it-trim_85CB6HmV_Mkub.mp4

Looks good. Please change first image to the following:

![GCI](https://user-images.githubusercontent.com/32364768/112013559-20457700-8b50-11eb-8bba-38d89b0cf7bd.PNG)

**Comment by drishtipeshwani** [comment]
Will do that

**Comment by vaishali614** [comment]
> Will do that

Are you done with the change?

**Comment by drishtipeshwani** [comment]
> > Will do that
> 
> Are you done with the change?

Yes I have made a pull request
