### ISSUE TITLE
Error while starting the application

### ISSUE THREAD

**Issue by Jassi10000-zz** [Girl-Code-It/Opportunity-Calendar-Frontend#109]
Am facing an issue while starting the application 
When I did " npm start "   to start the application , it returned this error

![issue1](https://user-images.githubusercontent.com/64856348/111077648-c32a3f80-8517-11eb-9280-b601556160ff.PNG)

**Comment by abdus** [comment]
@Jassi10000 can you tell me how to reproduce it? I freshly cloned the latest code and tried to reproduce it, but no success.

**Comment by Jassi10000-zz** [comment]
@abdus Brother  you mean , you are also facing the same issues ?

**Comment by Jassi10000-zz** [comment]
@Manvityagi  Mam can you please have a look on this issue ,  if  this doesnt get solved it will become very difficult for me to work on other issues

**Comment by abdus** [comment]
@Jassi10000 nope. I am not facing this issue. everything works fine in my end.

**Comment by Jassi10000-zz** [comment]
> @Jassi10000 can you tell me how to reproduce it? I freshly cloned the latest code and tried to reproduce it, but no success.

@abdus  Actually you mentioned here  that you got no success , that's why I asked 

Anyways , if it's working fine for you , please help me to resolve this , would be grateful to you

**Comment by abdus** [comment]
The latest codebase is running without errors ...

**Comment by Jassi10000-zz** [comment]
> The latest codebase is running without errors ...

@abdus Kindly help me with problem so that I can move forward to work on other issues as well

**Comment by Manvityagi** [comment]
> > The latest codebase is running without errors ...
> 
> @abdus Kindly help me with problem so that I can move forward to work on other issues as well

@Jassi10000 Can you elaborate more on what issue are you facing?

**Comment by Jassi10000-zz** [comment]
@Manvityagi Thanks mam for the concern , am actually facing this issue regularly , I even tried to fork again and run the application again , but the issue still persists and am not able to open the application on localhost 
That's why am tensed , coz if this issue will persist then I will not be able to work on other issues of this project

**Comment by Manvityagi** [comment]
> @Manvityagi Thanks mam for the concern , am actually facing this issue regularly , I even tried to fork again and run the application again , but the issue still persists and am not able to open the application on localhost
> That's why am tensed , coz if this issue will persist then I will not be able to work on other issues of this project

@Surajbokde Can you help him out? You can get in touch on Discord. Please try to solve @Jassi10000 problem asap @Surajbokde.

**Comment by Jassi10000-zz** [comment]
Thanks mam @Manvityagi  for helping me
one more thing mam , am not able to find  Girl-Code-It in the discord , can you please help with that too ?

**Comment by Manvityagi** [comment]
> Thanks mam @Manvityagi for helping me
> one more thing mam , am not able to find Girl-Code-It in the discord , can you please help with that too ?

**Comment by Manvityagi** [comment]
> > Thanks mam @Manvityagi for helping me
> > one more thing mam , am not able to find Girl-Code-It in the discord , can you please help with that too ?

#opportunity-calendar-frontend 
#opportunity-calendar-backend

These are the channel names on Discord, you can join them.

**Comment by Surajbokde** [comment]
@Jassi10000 just put your problems on our discord channel. i will help u there.

**Comment by Jassi10000-zz** [comment]
Thanks @Manvityagi , @Surajbokde I just msgd on Discord , can you please check that out

**Comment by abdus** [comment]
@Jassi10000 let me know if the issue is resolved.

**Comment by Jassi10000-zz** [comment]
@abdus , @Manvityagi   The issue is not solved yet ,  even  @Surajbokde  also tried , he's facing the same issue , even a frnd of his, is facing the same issue

**Comment by abdus** [comment]
Okay. Maybe tomorrow we can get on a call on Discord to resolve this. Let me know your availability.

**Comment by Jassi10000-zz** [comment]
@abdus  am available today between 4 -5

**Comment by Jassi10000-zz** [comment]
@abdus Sir am not able to catch anyone , who can help me , can you tell me the time when you are free today 
Am available between 8 -9 , can you schedule a meet to resolve my issue
@Manvityagi  mam can you plss help me regarding this issue ,  if @abdus  is not able to show up , can you assign a mentor to me who can have to meet to solve this , I will be vey grateful

**Comment by abdus** [comment]
hey, drop me a message on discord by 8pm.

**Comment by abdus** [comment]
I haven't heard back anything from @Jassi10000 after the initial conversation. So, I am going to close this issue. If you (or anyone else) is facing similar issues, please open a new issue. Please mention the steps to reproduce the error as well.
