### ISSUE TITLE
Change Favicon

### ISSUE THREAD

**Issue by lavanya243** [Girl-Code-It/Opportunity-Calendar-Frontend#111]
Hey @Manvityagi , @abdus , @vaishali614   , I am Lavanya Narayanan, a GSSOC, 2021 participant. I want to make changes in favicon in the website. Can I work on this issue?

**Comment by abdus** [comment]
Sure.

**Comment by shivansh-soni07** [comment]
, I am Shivansh Soni , a GSSOC, 2021 participant. I want to make changes in favicon in the website. Can I work on this issue?

**Comment by Manvityagi** [comment]
@shivansh-soni07 

Waiting for @lavanya243 to make a PR on this. If she doesn't make a PR by tomorrow night, I will assign it to you.
