### ISSUE TITLE
DARK MODE UI

### ISSUE THREAD

**Issue by mohammedjameel24** [Girl-Code-It/Opportunity-Calendar-Frontend#116]
##Dark Mode UI

**Comment by hansika31** [comment]
hi, I am Hansika, can I contribute to this project?

**Comment by Manvityagi** [comment]
Duplicate issue. So closing this one.

**Comment by Manvityagi** [comment]
> hi, I am Hansika, can I contribute to this project?

Sure @hansika31, go ahead. Look out for existing issues or explore the project and open new issues, get them assigned to you and make PRs. We love to have contributions.
