### ISSUE TITLE
Enhancing FAQ Section

### ISSUE THREAD

**Issue by shriya030** [Girl-Code-It/Opportunity-Calendar-Frontend#119]
### **Feature request**:
I want to add transition in FAQ section (when questions are being opened and closed) and also when one question is opened, the other one should automatically close. Also changing the cursor to pointer when the user hovers over the question.

### **Describe the solution you'd like**:
The changes will be made in CSS file i.e. transition will be applied and React Hooks will be used to add the feature of automatically closing a question, when other question is being opened.

### **Describe how this feature will be useful to our readers**:
This feature will enhance the readability of faqs and also the design of the website.

Please assign me this issue as a part of GSSOC'21.

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by shriya030** [comment]
@abdus @vaishali614 @Manvityagi Can I work on this issue?

**Comment by ShambhaviSharma0110** [comment]
Hey! I would really like to work on this please allow me to work on this as well...
-gssoc'21 participant

**Comment by Manvityagi** [comment]
> @abdus @vaishali614 @Manvityagi Can I work on this issue?

Go ahead @shriya030. Added the respective tags and assigned to you. 
Good Luck and feel free to communicate any doubts or ideas.

**Comment by Manvityagi** [comment]
> Hey! I would really like to work on this please allow me to work on this as well...
> -gssoc'21 participant

Hi @ShambhaviSharma0110, the issues assignment is on FCFS basis, please find another issue to work on.

**Comment by shriya030** [comment]
> > @abdus @vaishali614 @Manvityagi Can I work on this issue?
> 
> Go ahead @shriya030. Added the respective tags and assigned to you.
> Good Luck and feel free to communicate any doubts or ideas.

Thank you mam. I want you to review one thing. From where I can communicate with you? I had already started working on this issue. Should I make a pull request and then you can review it?

**Comment by Manvityagi** [comment]
> > > @abdus @vaishali614 @Manvityagi Can I work on this issue?
> > 
> > 
> > Go ahead @shriya030. Added the respective tags and assigned to you.
> > Good Luck and feel free to communicate any doubts or ideas.
> 
> Thank you mam. I want you to review one thing. From where I can communicate with you? I had already started working on this issue. Should I make a pull request and then you can review it?

You can join our discord channels on GSSOC server. 
#opportunity-calendar-frontend
#opportunity-calendar-backend

**Comment by Manvityagi** [comment]
Yes, @shriya030. Make a PR, We can review it then.
