### ISSUE TITLE
To add girl code it logo in title section as react logo is coming

### ISSUE THREAD

**Issue by saumyasrivastava08** [Girl-Code-It/Opportunity-Calendar-Frontend#124]
When we run npm start at corner logo of react is visible instead of girl code it . 
@Manvityagi can I work on this?

**Comment by Manvityagi** [comment]
> When we run npm start at corner logo of react is visible instead of girl code it .
> @Manvityagi can I work on this?

Have your previous PR merged and then you can start this.

**Comment by saumyasrivastava08** [comment]
please assign to me

**Comment by Manvityagi** [comment]
> please assign to me

Assigned, waiting for your PR @saumyasrivastava08

**Comment by saumyasrivastava08** [comment]
Pr is already there

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
