### ISSUE TITLE
Change transition of 'Know About' Cards

### ISSUE THREAD

**Issue by vaishali614** [Girl-Code-It/Opportunity-Calendar-Frontend#126]
- Keep color the same white
- Decrease the border radius ( in general ) 
- Give a size expansion and z index for shadow effect on hover

Refer this for clarity: https://www.capgridsolutions.com/enterprise-solution.html

**Comment by shriya030** [comment]
Can I work on this issue?

**Comment by vaishali614** [comment]
@shriya030 Sure. Go ahead.

**Comment by shriya030** [comment]
@vaishali614 you want sharp edges or a little bit curved edges for border-radius?

**Comment by shriya030** [comment]
![image](https://user-images.githubusercontent.com/56861600/111759665-d9dbe800-88c3-11eb-890f-a448fa6a54b6.png)
This much border-radius is okay? @vaishali614

**Comment by vaishali614** [comment]
> ![image](https://user-images.githubusercontent.com/56861600/111759665-d9dbe800-88c3-11eb-890f-a448fa6a54b6.png)
> This much border-radius is okay? @vaishali614

Yeah looks good.

**Comment by shriya030** [comment]
@vaishali614 Please review my PR

**Comment by vaishali614** [comment]
> @vaishali614 Please review my PR

Please pull the latest changes and update your PR so that all checks pass.

**Comment by shriya030** [comment]
> > @vaishali614 Please review my PR
> 
> Please pull the latest changes and update your PR so that all checks pass.

I am facing some problem, where can I contact you?

**Comment by vaishali614** [comment]
> > > @vaishali614 Please review my PR
> > 
> > 
> > Please pull the latest changes and update your PR so that all checks pass.
> 
> I am facing some problem, where can I contact you?

Connect with me on Discord.
