### ISSUE TITLE
Enhancing Navbar buttons

### ISSUE THREAD

**Issue by shriya030** [Girl-Code-It/Opportunity-Calendar-Frontend#127]
### **Feature request**:
Changing the color of navbar buttons and giving them a background upon hovering.

### **Describe the solution you'd like**:
Will make changes in the CSS file so that navbar buttons change their color upon hovering.

### **Describe how this feature will be useful to our readers**:
It will make the website look more appealing.

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by aj3011** [comment]
Can I work on this issue?

**Comment by vaishali614** [comment]
@aj3011 Sure. Go ahead.

**Comment by aj3011** [comment]
@vaishali614 There was a border-bottom effect applied on the navbar buttons but it wasn't working. So do you want me to fix that bug or to apply background color upon hovering?
![image](https://user-images.githubusercontent.com/71029690/111860943-ae630700-8970-11eb-8970-cd2e23561722.png)
or
![image](https://user-images.githubusercontent.com/71029690/111860993-eb2efe00-8970-11eb-88d8-13e2c8d45123.png)

**Comment by aj3011** [comment]
@vaishali614

**Comment by vaishali614** [comment]
> @vaishali614 There was a border-bottom effect applied on the navbar buttons but it wasn't working. So do you want me to fix that bug or to apply background color upon hovering?
> ![image](https://user-images.githubusercontent.com/71029690/111860943-ae630700-8970-11eb-8970-cd2e23561722.png)
> or
> ![image](https://user-images.githubusercontent.com/71029690/111860993-eb2efe00-8970-11eb-88d8-13e2c8d45123.png)

border-bottom looks better than adding a background. Fix that bug for border-bottom effect.

**Comment by aj3011** [comment]
@vaishali614 Please review my PR.
