### ISSUE TITLE
Redirect to main website

### ISSUE THREAD

**Issue by vaishali614** [Girl-Code-It/Opportunity-Calendar-Frontend#132]
1. Change the button text in About Us section: "Meet our Team" --> "Know More"
2. Redirect this button to https://girlcodeit.com/

**Comment by leoshrey** [comment]
I can work on this also, if no one proceeding

**Comment by vaishali614** [comment]
> I can work on this also, if no one proceeding

You've already been assigned an issue. Please finish that first.

**Comment by raks924** [comment]
Hey @vaishali614 i would really like to work on this as a first project. kindly assign it to me .
Under the team of GSSOC'21

**Comment by malavikarajeshvikraman** [comment]
Hey @vaishali614 could I work on this issue?

**Comment by vaishali614** [comment]
@raks924 @malavikarajeshvikraman Issues are assigned on FCFS basis. 
Assigning this issue to @raks924 
@malavikarajeshvikraman please find some other issue to work on.

**Comment by raks924** [comment]
thanks i'll solve it by today.

**Comment by vaishali614** [comment]
> thanks i'll solve it by today.

Deadline to finish a Level 1 issue is 2 days. If you're unable to make a PR by tonight, this issue will be assigned to someone else.
Please let us know if you're active on this issue.

**Comment by leoshrey** [comment]
I would like to work on this issue, if no one proceeding.

**Comment by vaishali614** [comment]
> I would like to work on this issue, if no one proceeding.

@raks924 has made a PR which is under review. If she fails to fix this issue, it'll be assigned to you.

**Comment by shriya030** [comment]
Can I work on this issue? I'll do it by today.

**Comment by vaishali614** [comment]
> Can I work on this issue? I'll do it by today.

We've a PR linked to this issue. It's under review. If she fails to get it approved by tonight, I'll assign it to you.
