### ISSUE TITLE
Add a Github action which automatically labels 'GSSOC21' to the newly created issue.

### ISSUE THREAD

**Issue by Karthik-Nayak98** [Girl-Code-It/Opportunity-Calendar-Frontend#137]
### **Feature request**:
Add a Github action which automatically labels 'GSSOC21'  for newly created issue.

### **Is your feature request related to a problem? Please describe. (optional)**:
Adding labels is an extra work for the maintainers, which can be avoided by GitHub action.

### **Describe how this feature will be useful to our readers**:
A clear and concise description of how this feature will be useful for our  other readers.

### **Additional context:**

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by Karthik-Nayak98** [comment]
If anyone wants to take this issue they can take it.

**Comment by ravjotsandhu** [comment]
I wanna take it up

**Comment by ravjotsandhu** [comment]
Also I updated my fork from web UI itself on github by making pr from orignal repo to my fork as it was some commits behind.Is this right way to proceed?

**Comment by abdus** [comment]
> Also I updated my fork from web UI itself on github by making pr from orignal repo to my fork as it was some commits behind.Is this right way to proceed?

it works .. nothing wrong.

**Comment by ravjotsandhu** [comment]
How can I check whether my gtihub action works?

**Comment by vaishali614** [comment]
@RavjotSandhu Any updates?

**Comment by Manvityagi** [comment]
> How can I check whether my gtihub action works?

You can check on your fork by changing the code for your fork.

**Comment by vaishali614** [comment]
@RavjotSandhu please respond by tomorrow otherwise I'll have to unassign you from this issue as per deadline rules.

**Comment by vaishali614** [comment]
@RavjotSandhu due to your inactiveness, i'm unassigning you from this issue.

**Comment by Inventor77** [comment]
@vaishali614 Mam I would love to work on this Issue Please Assign it to me

**Comment by AB-san** [comment]
I would like to work on this issue

**Comment by vaishali614** [comment]
@Inventor77 @AB-san  Issues are assigned on FCFS basis, so I'm assigning this issue to @Inventor77. If he fails to finish it within 2 days, it'll be assigned to @AB-san.
