### ISSUE TITLE
Change `About Us` content

### ISSUE THREAD

**Issue by vaishali614** [Girl-Code-It/Opportunity-Calendar-Frontend#141]
Replace the previous content with:

`If you feel like you keep missing on good opportunities that others grab easily only because you never find out about them in time, we got you covered!!

Opportunity Calendar provides instant information on newly posted opportunities for techies. Now you won't miss another deadline for applying to your dream companies. The calendar is your one-stop solution to know all about the latest Job openings, Internships, Scholarships, and all tech events including Tech Conferences, Hackathons, and other Coding Competitions.`

**Comment by leoshrey** [comment]
I will do the changes.

**Comment by vaishali614** [comment]
> I will do the changes.

Sure. Go ahead. Assigned to you.
