### ISSUE TITLE
Current search bar is clunky

### ISSUE THREAD

**Issue by leoshrey** [Girl-Code-It/Opportunity-Calendar-Frontend#144]
### **Feature request**:
A new Searching experience to the user by creating a more user-friendly and modern Search bar.

### **Is your feature request related to a problem? Please describe**:
Currently the Search Box we're using looks a bit broad, clunky and unsightly.
Whenever a user start typing in the field it adapts its shape according to the input which doesn't look good and provides bad experience. Also, it's not that responsive, especially when it comes to the mobile viewport.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/53581274/112440998-f61ecf80-8d70-11eb-9b99-79966581ca05.gif)

### **Describe the solution you'd like**:
I want to provide a new searching experience to the user by bringing an _interactive_ and _responsive_ search bar I already created.
Which will remove the clunkiness of the old one.

Here's a glimpse of search bar:

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/53581274/112444831-772b9600-8d74-11eb-9a82-034f5ba08983.gif)

- It will perfectly match the overall Color Scheme of our website.
- Will give interactive and flexible experience to the user.
- A little animation used here will provide nice experience to the user.
- The small space used here will help user focus on more important contents of the page.

@vaishali614, what are your thoughts on this?
If it's okay shall I start working ?

<hr/>

**Comment by vaishali614** [comment]
@leoshrey The new search bar looks great, but I feel the whole navbar needs to be revamped. 
Let me know if you can work on the whole navbar.

**Comment by leoshrey** [comment]
Ya, that's what I also thought, we should revamp the whole Navbar.
> Let me know if you can work on the whole navbar.

Sure, I'll work on that too.

I think I should create a specific issue for that, so that it can be simple.
Firstly, I should revamp the search bar (solve this issue) and then the whole Navbar.

What are your thoughts ?

**Comment by vaishali614** [comment]
> Ya, that's what I also thought, we should revamp the whole Navbar.
> 
> > Let me know if you can work on the whole navbar.
> 
> Sure, I'll work on that too.
> 
> I think I should create a specific issue for that, so that it can be simple.
> Firstly, I should revamp the search bar (solve this issue) and then the whole Navbar.
> 
> What are your thoughts ?

Okay, sounds good. Go ahead.

**Comment by leoshrey** [comment]
> Okay, sounds good. Go ahead.

Sure
