### ISSUE TITLE
Update Readme.md Rules Section

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Frontend#148]
In this [section](https://github.com/Girl-Code-It/Opportunity-Calendar-Frontend/blob/develop/README.md#rules), add one more rule at the end this way - 
- If you are creating a new issue, then please also comment on it mentioning that You want to work on it.

**Comment by Manvityagi** [comment]
@saumyasrivastava08 This is to be assigned to you as compensation for the last issue, Shall I assign it to you?

**Comment by saumyasrivastava08** [comment]
No it's okay let it be i solved lots of issue

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by saumyasrivastava08** [comment]
I am working on this
