### ISSUE TITLE
Update title `Girl Code It` to `Opportunity Calendar`

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Frontend#150]
![image](https://user-images.githubusercontent.com/32908093/112595767-df3fb200-8e30-11eb-9ca3-1d6b2834bb6e.png)

**Comment by saumyasrivastava08** [comment]
Can I work?

**Comment by Manvityagi** [comment]
> Can I work?

Assigned
