### ISSUE TITLE
Update What we Do? field in NavBar 

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Frontend#151]
In the Navbar Replace `What we do?` with `Opportunities` and link it to `Know About Section`. 

Refer the image for more clarity:
![image](https://user-images.githubusercontent.com/32908093/112595351-5163c700-8e30-11eb-9007-d7ffd84dff71.png)

**Comment by akshitakanojia** [comment]
Hi @Manvityagi , can I work on this issue?

**Comment by shriya030** [comment]
Can I work on this issue?

**Comment by Manvityagi** [comment]
> Hi @Manvityagi , can I work on this issue?

Go ahead @akshitakanojia :)

**Comment by YasmineEl-shahat** [comment]
Hi @Manvityagi , can I work on this issue?

**Comment by MennaMagdy2019** [comment]
Hi, can I work on this issue? @Manvityagi

**Comment by Manvityagi** [comment]
@MennaMagdy2019 , @YasmineEl-shahat , Someone else is already working on this issue, Please find a issue to which nobody is assigned yet or you can report a bug/feature-request/any other changes in the current project and open a issue for the same.
