### ISSUE TITLE
Logo Creation

### ISSUE THREAD

**Issue by divyasri77** [Girl-Code-It/Opportunity-Calendar-Frontend#155]
**ISSUE** : We can add a logo to your project to make it look more attractive</br>
**SOLUTION**: I will create a logo by using CANVA or by using ILLUSTRATOR
(GSSOC Participant)

**Comment by Hardik-07** [comment]
I would like to help in creating LOGO , can you plss assign me this issue

**Comment by divyasri77** [comment]
Can I work on it ? pls assign me

**Comment by abdus** [comment]
Duplicate of #84. Closing...
