### ISSUE TITLE
2 different pages is not required for login and signup

### ISSUE THREAD

**Issue by abhay27chauhan** [Girl-Code-It/Opportunity-Calendar-Frontend#159]
### **Feature request**:
2 different page is not required for login and signup. Can be implemented using single page

### **Is your feature request related to a problem? Please describe. (optional)**:
What it is now -> 

https://user-images.githubusercontent.com/42849043/112721075-f7dec380-8f27-11eb-8d8a-c7f35af671cb.mov

### **Describe the solution you'd like**:
My proposal -> 

It is quick and code is less

https://user-images.githubusercontent.com/42849043/112721416-94ee2c00-8f29-11eb-9c9d-ce50efd59ca1.mov

**Comment by abhay27chauhan** [comment]
Pls let me know if it is a valid proposal

**Comment by abdus** [comment]
Dividing code into multiple files makes it easier to maintain. Plus I don't think there is any common code block that is being copied in both files. So, I am going to close this issue. Please re-open this issue if you think I am missing something.

**Comment by abhay27chauhan** [comment]
both the files have same code except for firstname and last name in signup page

**Comment by abhay27chauhan** [comment]
plus the complete page is not reloading and its quick

**Comment by abhay27chauhan** [comment]
> Dividing code into multiple files makes it easier to maintain. Plus I don't think there is any common code block that is being copied in both files. So, I am going to close this issue. Please re-open this issue if you think I am missing something.

yes, it is good practice when it is reducing your code. but with different pages for signup and login you have to create an extra route for login + plus complete reload of your site + same code twice in different files.

**Comment by abdus** [comment]
those pages are not complete yet. there is logic to be added for sign-in and sign-up functionality. and that would probably make the file huge. 

anyways, I will go ahead and reopen this issue. I can't assign it to you right away as you have another one assigned to you. However, you can claim it once the other issue assigned to you is closed (obviously if no-one else claims it...)

**Comment by akshay1027** [comment]
can you please assign me this issue?

**Comment by vaishali614** [comment]
> ### **Feature request**:
> 2 different page is not required for login and signup. Can be implemented using single page
> 
> ### **Is your feature request related to a problem? Please describe. (optional)**:
> What it is now ->
> 
>  Screen.Recording.2021-03-27.at.6.11.57.PM.mov 
> ### **Describe the solution you'd like**:
> My proposal ->
> 
> It is quick and code is less
> 
>  Screen.Recording.2021-03-27.at.6.23.09.PM.mov

I agree with what @abdus said. Also, as per your solution, both have same path i.e. '/signup'. We don't want that.

**Comment by abhay27chauhan** [comment]
> > ### **Feature request**:
> > 2 different page is not required for login and signup. Can be implemented using single page
> > ### **Is your feature request related to a problem? Please describe. (optional)**:
> > What it is now ->
> > Screen.Recording.2021-03-27.at.6.11.57.PM.mov
> > ### **Describe the solution you'd like**:
> > My proposal ->
> > It is quick and code is less
> > Screen.Recording.2021-03-27.at.6.23.09.PM.mov
> 
> I agree with what @abdus said. Also, as per your solution, both have same path i.e. '/signup'. We don't want that.

we can change the path to '/auth'

**Comment by abdus** [comment]
hey @abhay27chauhan, we(mentors) had a discussion around this proposal, and we concluded that merging these two pages(or components) is not necessary for now. We may open this issue again in future if needed. Thank you for your contributions.

closing...
