### ISSUE TITLE
 animation on viewOppertunity Card 

### ISSUE THREAD

**Issue by MennaMagdy2019** [Girl-Code-It/Opportunity-Calendar-Frontend#161]
# Prerequisites:

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked to make sure that this issue has not already been filed.

- [x] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# Expected Behavior:

Can I make an animation on view opportunity Card on haver?

# Current Behavior:

view opportunity Card without animation on haver

# Solution:
I make   animation on view opportunity Card  on haver using transform and transition to scale 1.1 on hover and make keyframe on load card from left:-1000px to 0 and change a color card for gray

# Screenshots (optional):
![Capture](https://user-images.githubusercontent.com/50016070/112813907-02f83780-907f-11eb-8f6f-3652d15147d6.PNG)

to 
![Capture1](https://user-images.githubusercontent.com/50016070/112815294-72baf200-9080-11eb-8f8a-10b9a3a3f028.PNG)

 @GSSOC

**Comment by MennaMagdy2019** [comment]
please, I want to work on this issue I am interested to work on it

**Comment by MennaMagdy2019** [comment]
I think it will look nice. Do assign me this issue Thank you

**Comment by vaishali614** [comment]
@MennaMagdy2019 Thanks for raising this issue. Well, we're revamping the whole page, so we've planned a different animation for cards.  I suggest you to wait until the page is revamped and post that we can work on cards animation.

I'm closing this issue for now. We'll open this issue again when needed.
