### ISSUE TITLE
View Opportunity Page Revamp

### ISSUE THREAD

**Issue by vaishali614** [Girl-Code-It/Opportunity-Calendar-Frontend#164]
Revamping of View Opportunity Page:

1. `Post Opportunity` button should redirect to `Post Opportunity` page of respective opportunity.
2. `Select Opportunity` dropdown should have: 
- Fulltime Jobs
- Hackathons
- Scholarships
- Coding Competitions
- Tech Conferences
- Internships
3. The banner heading should change accordingly.
4. Must be responsive for all screen sizes.

[Follow this design](https://www.figma.com/proto/XKmx5ia2hGjM9iz3VdWABp/girlcodeit?node-id=11%3A62&scaling=min-zoom&page-id=0%3A1)

**Comment by MennaMagdy2019** [comment]
Hi @vaishali614, Can I work on this issue?

**Comment by vaishali614** [comment]
@MennaMagdy2019 Sure. Go ahead.

**Comment by MennaMagdy2019** [comment]
sorry, Can you assign me again? @vaishali614

**Comment by MennaMagdy2019** [comment]
Thanks @vaishali614

**Comment by akshitakanojia** [comment]
Hi @vaishali614 , can I work on this issue?
