### ISSUE TITLE
Post Opportunity Page Revamp

### ISSUE THREAD

**Issue by vaishali614** [Girl-Code-It/Opportunity-Calendar-Frontend#165]
Revamping of Post Opportunity Page:

1. `Find Opportunity` button should redirect to `View Opportunity` page of respective opportunity.
2. Dropdown should have the following values which will redirect to `Post Opportunity` page of those opportunities: 
- JOB
- INTERNSHIP
- HACKATHON
- SCHOLARSHIP
- CODINGCOMPETITION
- CONFERENCE
3. `Find Opportunity` button in navbar should redirect to only that opportunity of which user is posting the opportunity.
4. Must be responsive for all screen sizes.

[Follow this design](https://www.figma.com/proto/XKmx5ia2hGjM9iz3VdWABp/girlcodeit?node-id=602%3A55&scaling=min-zoom&page-id=0%3A1)

**Comment by YasmineEl-shahat** [comment]
Hi @vaishali614, Can I work on this issue?

**Comment by AshuKV** [comment]
Can I work on this issue under GSSOC21? Kindly assign it to me.

**Comment by vaishali614** [comment]
@YasmineEl-shahat @AshuKV Issues are assigned on FCFS basis, so I'm assigning this issue to @YasmineEl-shahat

**Comment by YasmineEl-shahat** [comment]
thank you @vaishali614

**Comment by vaishali614** [comment]
@AshuKV This issue is up for grabs. Please comment if you still wanna take this up.

**Comment by AshuKV** [comment]
I want to work on this issue. Please assign it to me.

**Comment by vaishali614** [comment]
@AshuKV What's the status of PR on this issue?

**Comment by vaishali614** [comment]
> @AshuKV What's the status of PR on this issue?

@AshuKV Please show your activeness by making a PR by tomorrow, otherwise I'll have to unassign you as per deadline rules.

**Comment by AshuKV** [comment]
Hey @vaishali614 I am currently working on this issue, will push the code by EOD today.

**Comment by wajeehamushtaq** [comment]
I am GSSOC'21 participant. If this issue still open please assign this issue to me

**Comment by vaishali614** [comment]
@wajeehamushtaq Sure, go ahead.

**Comment by vaishali614** [comment]
@wajeehamushtaq any updates?

**Comment by vaishali614** [comment]
@wajeehamushtaq due to your inactiveness, I'm unassigning you from this issue.

**Comment by Sukriti-sood** [comment]
I want to work on this.

**Comment by vaishali614** [comment]
@Sukriti-sood Any updates?

**Comment by Sukriti-sood** [comment]
@vaishali614  Half is done , Will try to complete it by today.

**Comment by vaishali614** [comment]
> @vaishali614 Half is done , Will try to complete it by today.

Great. Looking forward to your PR.
