### ISSUE TITLE
feat: Adding hover effect to opportunity  card

### ISSUE THREAD

**Issue by iampranavdhar** [Girl-Code-It/Opportunity-Calendar-Frontend#166]
### **Feature request**:
Hey @abdus,@vaishali614,
I am Pranavdhar. While I was going through the website I found that opportunity cards are not given hover effects. Can we add a hover effect to it? as it increases the interactivity If you wanna add this you can assign it to me I am happy to work on it.

### Snapshot of What I am talking about:

![image](https://user-images.githubusercontent.com/73348574/112889068-c9f9aa80-90f2-11eb-8249-d8557bd23ca0.png)

Thanks

**Comment by vaishali614** [comment]
@iampranavdhar Thanks for raising this issue. Well, we're revamping the whole page, so animations will be added later. I suggest you to wait until the page is revamped. Until then, you can raise some other issue.
I'm closing this issue for now. Will open it again when needed.

**Comment by iampranavdhar** [comment]
Okay
