### ISSUE TITLE
Adding animated social media icons in footer and animated illustrations instead of static images

### ISSUE THREAD

**Issue by sonalisonawane** [Girl-Code-It/Opportunity-Calendar-Frontend#167]
I can add animated social media icons in footer section also animated illustrations, It really looks attractive

social icons used to promote our work on social networks and get in return potential customers. So , I thought there should be something to make it attractive
You can assign this issue under gssoc label

**Comment by vaishali614** [comment]
@sonalisonawane can you please show what kind of animation will you be adding to make it attractive?

**Comment by sonalisonawane** [comment]
@vaishali614  mam ,You may go through the demo video on this website about what kind of animated icons I will going to add .
and about animated illutrations:
 https://motionarray.com/motion-graphics-templates/10-animated-social-media-icons-150310

you can check my this repo it contains only the animated illustration that I am going to add,we can change color of it according to the color theme of our website :) 
https://github.com/sonalisonawane/example.git

**Comment by vaishali614** [comment]
> @vaishali614 mam ,You may go through the demo video on this website about what kind of animated icons I will going to add .
> and about animated illutrations:
> https://motionarray.com/motion-graphics-templates/10-animated-social-media-icons-150310
> 
> you can check my this repo it contains only the animated illustration that I am going to add,we can change color of it according to the color theme of our website :)
> https://github.com/sonalisonawane/example.git

@DeepanshiD Please check these. What are your opinions on this?
@sonalisonawane The deployed link for your github repo doesn't work.
CC: @Manvityagi

**Comment by sonalisonawane** [comment]
@vaishali614 mam , 
https://storyset.com/search?q=developer
or 
https://design4users.com/motion-design-20-inspiring-animated-illustrations/
I am  sorry for that repo link . can you go please go through this links, this kind of animation illustrations we can use add instead of static image :)

**Comment by vaishali614** [comment]
@sonalisonawane Okay.. Go ahead. I'm not sure if it would look good, but let's see what do you come up with.

**Comment by DeepanshiD** [comment]
@sonalisonawane This seems nice, you can go with this, but keep the border radius and color scheme consistent to the whole website.

**Comment by sonalisonawane** [comment]
> @sonalisonawane Okay.. Go ahead. I'm not sure if it would look good, but let's see what do you come up with.

thanks mam:)

**Comment by sonalisonawane** [comment]
> @sonalisonawane This seems nice, you can go with this, but keep the border radius and color scheme consistent to the whole website.

yes I will, thanks mam:)

**Comment by sonalisonawane** [comment]
@vaishali614 mam do I have to change in opportunity calendar frontend ???
