### ISSUE TITLE
Making Icons Properly aligned

### ISSUE THREAD

**Issue by Naman-1234** [Girl-Code-It/Opportunity-Calendar-Frontend#168]
### **Feature request**:

All icons except the last one are in center, hence giving last one improper look.

### **Is your feature request related to a problem? Please describe. (optional)**:

Please refer screenhot:
![Screenshot (48)](https://user-images.githubusercontent.com/63748249/113061590-eddeee00-91cf-11eb-88a6-e6606dba6f80.png)

### **Describe the solution you'd like**:

Please refer screenshot:
![Screenshot (47)](https://user-images.githubusercontent.com/63748249/113061630-f8998300-91cf-11eb-9ca5-07244575c709.png)

### **Describe alternatives you've considered**:

Please refer screenshot provided in the solution.
### **Describe how this feature will be useful to our readers**:

Will improve UI.

### **Additional context:**

Screenshots are already provided/
<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by Naman-1234** [comment]
Can you assign me on this one.I am a gssoc participant. Thanks.

**Comment by Manvityagi** [comment]
CC: @DeepanshiD What do you think?

**Comment by DeepanshiD** [comment]
@Naman-1234 sure you can pick up the task, keep icons in white and center aligned. You have to pick up icons from https://remixicon.com/
