### ISSUE TITLE
Making button center Aligned in a contact us page

### ISSUE THREAD

**Issue by Naman-1234** [Girl-Code-It/Opportunity-Calendar-Frontend#170]
### **Feature request**:

Center Alignment of button
### **Is your feature request related to a problem? Please describe. (optional)**:

Please refer to the screenshot:
![Screenshot (51)](https://user-images.githubusercontent.com/63748249/113115865-7e4a1c80-922a-11eb-8897-00c4888f4287.png)

### **Describe the solution you'd like**:

Please refer to the following screenshot:
![Screenshot (50)](https://user-images.githubusercontent.com/63748249/113115905-8b670b80-922a-11eb-8a94-0066bd16b48f.png)

### **Describe how this feature will be useful to our readers**:

Will Improve UI.

### **Additional context:**

Screenshots are already provided.

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by Naman-1234** [comment]
If this is a valid Issue. I would like to work on this one. Could you assign me Please. I am a GSSOC Participant. Thanks.

**Comment by vaishali614** [comment]
@DeepanshiD what do you think about alignment of button?

**Comment by DeepanshiD** [comment]
@Naman-1234 the edit one should also start from the beginning. For example the padding of mail icon is 4px from top in box, so it should be same for edit/pencil icon
CC: @vaishali614

**Comment by DeepanshiD** [comment]
@Naman-1234 Alignment of button on the left is fine, so I'm closing this issue.
CC @vaishali614
