### ISSUE TITLE
Scroll Bar

### ISSUE THREAD

**Issue by shriya030** [Girl-Code-It/Opportunity-Calendar-Frontend#171]
### **Feature request**:

An attractive scroll bar (Blue and White-colored). I would like to add this as a GSSOC'21 participant

### **Describe how this feature will be useful to our readers**:

It will make the webpage look more attractive.

### **Additional context:**

![image](https://user-images.githubusercontent.com/56861600/113123478-421aba00-9232-11eb-9abc-1706ba7b5ced.png)

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by shriya030** [comment]
Can I work on this?

**Comment by vaishali614** [comment]
@DeepanshiD What do you think about this?
CC: @Manvityagi @abdus

**Comment by shriya030** [comment]
> @DeepanshiD What do you think about this?
> CC: @Manvityagi @abdus

I can customize it in whichever way you like, less width or any other colour.

**Comment by DeepanshiD** [comment]
@shriya030 Scroll bar looks great when minimal, an ideal scroll bar has a shade of grey (without gradient), width 6px, border radius 2px. You can choose this as it is or try to play around with width and radius.

**Comment by shriya030** [comment]
Please assign me this issue.

> @shriya030 Scroll bar looks great when minimal, an ideal scroll bar has a shade of grey (without gradient), width 6px, border radius 2px. You can choose this as it is or try to play around with width and radius.

Can I work on this issue?

**Comment by vaishali614** [comment]
> Please assign me this issue.
> 
> > @shriya030 Scroll bar looks great when minimal, an ideal scroll bar has a shade of grey (without gradient), width 6px, border radius 2px. You can choose this as it is or try to play around with width and radius.
> 
> Can I work on this issue?

Go ahead

**Comment by shriya030** [comment]
@DeepanshiD @vaishali614 have a look.
