### ISSUE TITLE
Adding more FAQs 

### ISSUE THREAD

**Issue by aj3011** [Girl-Code-It/Opportunity-Calendar-Frontend#173]
# Expected Behavior:

Adding more FAQs as per https://girlcodeit.com/#faqs

# Current Behavior:

What is the current behavior? 
Fewer FAQs present in the section currently

# Solution: 
I will make the required changes in the FAQ data file

**Comment by aj3011** [comment]
Please assign me this issue as a part of GSSOC' 21

**Comment by vaishali614** [comment]
> Please assign me this issue as a part of GSSOC' 21

@aj3011 Please update the FAQs as below:

1. What is Opportunity Calendar? 
Exactly what the title says : It's a calendar filled with opportunities in the tech industry for you! 

2. Why is it needed? 
Many a times, it's not that we don't have the right opportunities - it's that we don't know about them. The opportunity calendar serves the purpose of eliminating this hurdle- by keeping you abreast with all the latest relevant opportunities in the technology world. 

3. How can you benefit? 
The way we see it - the benefits are endless. Want to pursue your passion in coding? We're sure you'll find something here suited to your needs. Want to know what companies look for in their ideal candidate? You'll find it here! 
It all depends on you from there on out! 

4. How can you contribute? 
This is the easiest job in the world. Keep your eyes and ears perked up for such opportunities, and once spotted, give one of us a heads up! As simple as that :)

**Comment by aj3011** [comment]
Okay! Will do it. @vaishali614 Please assign this to me.
