### ISSUE TITLE
communities

### ISSUE THREAD

**Issue by Pratishtha33** [Girl-Code-It/Opportunity-Calendar-Frontend#180]
### **Is your feature request related to a problem? Please describe. (optional)**:

the problem is, students as a fresher don't know the path to learn new skills. they lose motivation and they stop learning new things every day.

### **Describe the solution you'd like**:

so, I would like to add the communities section to the website so that students will join the communities according to their interests.  I have realized that being part of any community we stay motivated and learn new things every day.

### **Describe how this feature will be useful to our readers**:

we will have the opportunity to learn new skills in a variety of formats. You’ll also meet local developers virtually or in
-person with similar interests in technology.

### **Additional context:**

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by abdus** [comment]
we have a website for that. http://girlcodeit.com/

**Comment by Manvityagi** [comment]
We can add somewhere on the homepage the link to our codemaps on main website. 

Cc: @DeepanshiD @abdus

**Comment by Pratishtha33** [comment]
As you mentioned on your separate website that everything needs a structure to work properly. we can add it on the navbar of the opportunity calendar. as (community )so the visitor will find it convenient and helpful. @abdus @Manvityagi 😇
user will find everything in one place and this web will be all in one.

**Comment by vaishali614** [comment]
Our main website is already linked through `Know more` button of About section. And as soon as we're able to complete this one, we'll link it with our main website too. So both are already linked together. So, I'm closing this issue.
