### ISSUE TITLE
Hide and show password functionality button in form

### ISSUE THREAD

**Issue by abhay27chauhan** [Girl-Code-It/Opportunity-Calendar-Frontend#184]
### **Feature request**:

Hide and show password functionality button in form

**Comment by vaishali614** [comment]
@abhay27chauhan do you wanna take this issue?

**Comment by abhay27chauhan** [comment]
Yes

**Comment by abhay27chauhan** [comment]
@vaishali614 what should use for the icon ?

**Comment by abhay27chauhan** [comment]
@vaishali614 done.
