### ISSUE TITLE
Github profile Links and design links in the readme to open in a new tab 

### ISSUE THREAD

**Issue by akshay1027** [Girl-Code-It/Opportunity-Calendar-Frontend#185]
# Prerequisites:

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [] I checked to make sure that this issue has not already been filed.

- [x] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# Expected Behavior:

Please describe the behavior you are expecting.
Links in the readme to open in a new tab so that it is easier for the user to navigate to GitHub codebase.

**Comment by vaishali614** [comment]
@akshay1027 Do you wanna take up this issue?

**Comment by akshay1027** [comment]
yes! but i found that we cant do like this in github! here is the link to that: https://github.com/mojombo/github-flavored-markdown/issues/28

**Comment by vaishali614** [comment]
> yes! but i found that we cant do like this in github! here is the link to that: [mojombo/github-flavored-markdown#28](https://github.com/mojombo/github-flavored-markdown/issues/28)

Yeah! So, I'm closing this issue then. Please open another issue to work on.
