### ISSUE TITLE
Space between navbar elements 

### ISSUE THREAD

**Issue by aastha-io** [Girl-Code-It/Opportunity-Calendar-Frontend#187]
### **Feature request**:
A clear and concise description of the feature.

I want to add left spacing in the navbar it is too close to the ends

### **Is your feature request related to a problem? Please describe. (optional)**:

A clear and concise description of what the problem is.

### **Describe the solution you'd like**:

I will add space to it 

### **Describe how this feature will be useful to our readers**:
A clear and concise description of how this feature will be useful for our other readers.

It will look better 

### **Additional context:**

<img width="366" alt="Capture3" src="https://user-images.githubusercontent.com/72413064/113511339-fee78080-957c-11eb-9418-eb7da07eae89.PNG">

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by vaishali614** [comment]
@AasthaCodex I think it already has enough spacing, we don't need any more spacing. So I'm closing this issue. Please find some other issue to work on.
