### ISSUE TITLE
Want to implement react context api

### ISSUE THREAD

**Issue by abhay27chauhan** [Girl-Code-It/Opportunity-Calendar-Frontend#188]
### **Feature request**:

Want to implement react context api @abdus

**Comment by abdus** [comment]
for what exactly?

**Comment by abhay27chauhan** [comment]
So that I can complete that user wala part

**Comment by vaishali614** [comment]
@abhay27chauhan It would have been better if you would have given reference to the issue you are talking about. In fact, whenever you create an issue, give proper reasoning to what you wanna add and how will it benefit.

**Comment by abhay27chauhan** [comment]
I did not give a reason as you don't have either react context api or redux
in your app, and you are not going with redux as told by one of your team
mate so I thought that it is obvious that you would like to implement react
context api. So I opened the issue

**Comment by vaishali614** [comment]
Okay, but please make sure you give proper explanation to an issue created by you from next time.
Assigning this issue to you. You can start working on it.

**Comment by abhay27chauhan** [comment]
@vaishali614 is it ok ?

**Comment by abhay27chauhan** [comment]
@vaishali614  ??
