### ISSUE TITLE
Add chatbot feature to the website for the convenience of users 

### ISSUE THREAD

**Issue by WebVishal** [Girl-Code-It/Opportunity-Calendar-Frontend#191]
hi I'm Vishal, I think it should have a chatbot feature so that it can interact with the user easily and be able to convince well
can I work on this idea as Gssoc'21 Participant?

**Comment by vaishali614** [comment]
@WebVishal Thanks for opening this issue. Upon discussing with other mentors, we came to a conclusion that this feature doesn't seem much relevant to the project requirements. So I'm closing this issue. Please find some other issue to work on.
