### ISSUE TITLE
Responsiveness and design of the website

### ISSUE THREAD

**Issue by Avishake007** [Girl-Code-It/Opportunity-Calendar-Frontend#192]
I think the divs in the know about portion when seen in smaller device will look better if they are placed center.
I also want to work on the design of the website.
Please assign me for this issue under gssoc'21.

**Comment by vaishali614** [comment]
> I think the divs in the know about portion when seen in smaller device will look better if they are placed center.
> I also want to work on the design of the website.
> Please assign me for this issue under gssoc'21.

Yeah. We need to fix that. Please go ahead. Don't change any design, just correct the responsiveness wherever required.

**Comment by vaishali614** [comment]
@Avishake007 Are you working on this issue?
