### ISSUE TITLE
Redesign of the job/opportunity card and make it complement the whole website.

### ISSUE THREAD

**Issue by mohitms007** [Girl-Code-It/Opportunity-Calendar-Frontend#194]
### **Feature request**:

A clear and concise description of the feature.
  The card component in the website which is shown for different jobs and opporutunities doesn't look ideal and the image can be rounded instead of a square which doesn't look good. The details and apply button too can see improvement and look more inclusive and professional.

### **Is your feature request related to a problem? Please describe. (optional)**:
N/A
A clear and concise description of what the problem is.
N/A

### **Describe the solution you'd like**:
I want to make the card much more professional by aligning it so that it looks good and complements the design of this website.

### **Describe alternatives you've considered**:
Will check different alignements and design which look the best and then come to the best design about the card.

### **Describe how this feature will be useful to our readers**:
A clear and concise description of how this feature will be useful for our other readers.
The square image doesn't look more professional and the card could see visual improvements so that users can easily see what is the job, who it is from and how to apply while looking genuinely impressive.

### **Additional context:**

The job card doesn't look professional.
![Screenshot from 2021-04-07 12-50-47](https://user-images.githubusercontent.com/55339354/113828293-db514f80-97a1-11eb-9802-2f7ad1b07855.png)

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by mohitms007** [comment]
Please assign this to me.

**Comment by Manvityagi** [comment]
> Please assign this to me.

Good catch, Go ahead @mohitms007

**Comment by mohitms007** [comment]
Thanks I will start working on it!
