### ISSUE TITLE
Adding mouse move over effect

### ISSUE THREAD

**Issue by wajeehamushtaq** [Girl-Code-It/Opportunity-Calendar-Frontend#195]
### **Feature request**:

Adding mouse move over effect on images and cards used in the site

### **Describe the solution you'd like**:

Adding some javascript and CSS for adding 3D perspective. So the cards and images used on the site will look 3D in perspective.

**Comment by wajeehamushtaq** [comment]
Please assign this issue to me

**Comment by vaishali614** [comment]
@DeepanshiD what are your views on this?

**Comment by DeepanshiD** [comment]
@wajeehamushtaq There are already a lot of animations and hover effects used in the website any more of it will be an overdo, we don't need anymore hover or mouse move over effects.
CC @vaishali614

**Comment by vaishali614** [comment]
@wajeehamushtaq I agree with @DeepanshiD, so I'm closing this issue. Please find some other issue to work on.
