### ISSUE TITLE
Redesign Footer of the site

### ISSUE THREAD

**Issue by wajeehamushtaq** [Girl-Code-It/Opportunity-Calendar-Frontend#197]
### **Feature request**:

I am a GSSOC'21 participant and want to redesign the footer of the site according to the XD design.

![gss](https://user-images.githubusercontent.com/55188521/114073240-80f8e180-98bc-11eb-87b0-9dc6c9e9cb54.JPG)

**Comment by vaishali614** [comment]
@wajeehamushtaq This was our previous design and the current design has been updated by one of GSSoC participants only. I apologize because the designs mislead you. I'll get them updated.
