### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by vaishali614** [Girl-Code-It/Opportunity-Calendar-Frontend#198]
1. Redirect CodeMaps to: "https://girlcodeit.com/codemaps"
2. Redirect Opportunity Calendar to: "/" i.e. the homepage itself
3. Convert headings (PRODUCT, LINKS and CONTACT US) to normal case (Products, Links, Contact Us)
4. Underline Contact Us too
5. Redirect logo to: https://girlcodeit.com/
6. Align copyright icon with '2021 Girl Code It'

**Comment by vaishali614** [comment]
@wajeehamushtaq Since 2 issues opened by you were closed back to back, I've opened this issue and would like you to work on this. Please comment below if you wanna take up this issue.

**Comment by wajeehamushtaq** [comment]
Yes I want to work on it
