### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [Girl-Code-It/Opportunity-Calendar-Frontend#204]
Hi I would like to  add the following in contributing.md-
Difference between GIT and GITHUB
How to clone,fork repository
How to create a branch and then use git push to push to repo
Create a PR
Squash commits in a single issue into one
Updating the forked and local repo as the updations are made in the upstream

**Comment by vaishali614** [comment]
@khareyash05 We already have contributing.md, in case you missed it. It already includes few of the things mentioned by you. 

You can add the following -
1. Difference between GIT and GITHUB
2. Squash commits in a single issue into one
3. Updating the forked and local repo as the updations are made in the upstream
4. You can include the link to this video too: https://www.youtube.com/watch?v=ZeHPcMZ-qlE
