### ISSUE TITLE
Arrangement of Buttons in HomePage

### ISSUE THREAD

**Issue by anhushree** [Girl-Code-It/Opportunity-Calendar-Frontend#205]
- [x] I checked to make sure that this issue has not already been filed.

- [x] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# Expected Behavior:

Please describe the behavior you are expecting.
The Explore button should be moved to its left, Know More button should be moved up and aligned with the blue line above it right now.

# Current Behavior:

What is the current behavior?
The Explore Button is placed on the right-hand side which leaves so much unwanted space.
The Know More button is placed below the Blue line which is visually displeasing. 

# Solution:

Please describe what will you do to solve this issue or your approach to solve this issue.
I'll move the Explore button to the left side and make sure it's aligned with the text. The Know more button will be brought slightly up so that it aligns with the blue line giving a better visual appearance

# Screenshots (optional):
![image](https://user-images.githubusercontent.com/56672958/114341385-44a4da00-9b77-11eb-9bab-c31a3c6d000d.png)
![image](https://user-images.githubusercontent.com/56672958/114341389-479fca80-9b77-11eb-93da-4ac5e02fc9f5.png)

**Comment by vaishali614** [comment]
@anhushree The two buttons are knowingly placed like that. However, `Know More` button seems distorted in mobile view. Let me know if you wanna work upon that.

The button should be shifted above a bit and left aligned with the text.
![3Capture](https://user-images.githubusercontent.com/32364768/114458866-6648a480-9bfd-11eb-93f0-4171bbe3bf2e.PNG)

**Comment by anhushree** [comment]
![image](https://user-images.githubusercontent.com/56672958/114487182-c73ba100-9c2c-11eb-9101-fa4dac552c8b.png)
I was referring to the spaces between the words 
for eg, in the above image we can see there is a double space between "if  you  feel   like   you   keep   missing   on   good" in the first paragraph

**Comment by anhushree** [comment]
yes sure, I would like to work on this issue.

**Comment by vaishali614** [comment]
> yes sure, I would like to work on this issue.

Any updates?
