### ISSUE TITLE
Double Spaces in About Us paragraphs

### ISSUE THREAD

**Issue by anhushree** [Girl-Code-It/Opportunity-Calendar-Frontend#206]
- [x] I checked to make sure that this issue has not already been filed.

- [x] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# Expected Behavior:

Please describe the behavior you are expecting.
Reduced double spaces in the About Us paragraph

# Current Behavior:

What is the current behavior?
The About Us content has an extra space between the words.
# Solution:

Please describe what will you do to solve this issue or your approach to solve this issue.
Removal of Unwanted Spaces between the words in About Us will reduce the Extra Space.

# Screenshots (optional):
![image](https://user-images.githubusercontent.com/56672958/114342216-1922ef00-9b79-11eb-9e84-b183ee825637.png)

**Comment by vaishali614** [comment]
@anhushree If you're talking about the space between two paragraphs, then it's not unwanted. So, I'm closing this issue. Let me know if I'm wrong.

**Comment by anhushree** [comment]
![image](https://user-images.githubusercontent.com/56672958/114487182-c73ba100-9c2c-11eb-9101-fa4dac552c8b.png)
I was referring to the spaces between the words 
for eg, in the above image we can see there is a double space between "if  you  feel   like   you   keep   missing   on   good" in the first paragraph

**Comment by anhushree** [comment]
@vaishali614, Could you kindly check this issue once again?

**Comment by vaishali614** [comment]
> ![image](https://user-images.githubusercontent.com/56672958/114487182-c73ba100-9c2c-11eb-9101-fa4dac552c8b.png)
> I was referring to the spaces between the words
> for eg, in the above image we can see there is a double space between "if you feel like you keep missing on good" in the first paragraph

That's because the text is justified. Let me know if you can remove those extra spaces and it'll remain justified.
