### ISSUE TITLE
Preloader feature

### ISSUE THREAD

**Issue by archanagandhi** [Girl-Code-It/Opportunity-Calendar-Frontend#215]
Hey @vaishali614,
I would like to add the preloader effect to the website,. Please assign this to me.
Thanks

**Comment by vaishali614** [comment]
@archanagandhi Go ahead

**Comment by vaishali614** [comment]
@archanagandhi any updates?

**Comment by vaishali614** [comment]
@archanagandhi Due to your inactiveness, I'm unassigning you from this issue.

**Comment by shriya030** [comment]
Can I work on this issue?

**Comment by vaishali614** [comment]
@shriya030 Go ahead

**Comment by shriya030** [comment]
> @shriya030 Go ahead

So I have to apply the preloader feature on every page and Can I choose the design on my own?

**Comment by vaishali614** [comment]
> > @shriya030 Go ahead
> 
> So I have to apply the preloader feature on every page and Can I choose the design on my own?

Yeah, it should be implemented on every page. Sure, come up with your design, we'll recommend changes if required.

**Comment by vaishali614** [comment]
@shriya030 Any updates?

**Comment by shriya030** [comment]
> @shriya030 Any updates?

I was busy with some college assignments. I'll update you tomorrow.

**Comment by vaishali614** [comment]
@shriya030 Haven't got any update yet. Are you still busy with something else? Please let me know so that I can unassign you and someone can pick this up.

**Comment by shriya030** [comment]
@vaishali614 It's not working for me. I have tried alot. You can assign it to someone else.
