### ISSUE TITLE
Remaking of Sign Up and  Sign In page 

### ISSUE THREAD

**Issue by kumarishalini6** [Girl-Code-It/Opportunity-Calendar-Frontend#216]
### **Feature request**:
The sign up and sign in page should be more graceful and must have validations.
I want to work on this issue under GSSoC'21 participant can i ?

**Comment by vaishali614** [comment]
@kumarishalini6 Can you please show a glimpse of the change you wanna make?

**Comment by kumarishalini6** [comment]
The pages are too short in full screen i want to make it perfect according to screen and want to add some images like:-
![React App - Personal - Microsoft​ Edge 4_17_2021 06_39_03 PM](https://user-images.githubusercontent.com/69043944/115114426-d1ff7a00-9f3b-11eb-837f-c4bacf3956dd.png)

**Comment by kumarishalini6** [comment]
I'll send you the final image  after working on it

**Comment by kumarishalini6** [comment]
now can i work on it?

**Comment by vaishali614** [comment]
@kumarishalini6 Looks good. But you've already been assigned an issue, so you'll have to first finish that one and then you can start with this one.

**Comment by kumarishalini6** [comment]
I have fixes#217 now assign me

**Comment by vaishali614** [comment]
> I have fixes#217 now assign me

I have requested a few changes, once that PR gets merged, this issue will be assigned to you.

**Comment by kumarishalini6** [comment]
Ok

**Comment by SanskritiKushik5** [comment]
Can I work over this issue as a GSSOC'21 participant?

**Comment by kumarishalini6** [comment]
i have send PR please review it.

**Comment by kumarishalini6** [comment]
Please review my PR
