### ISSUE TITLE
Navbar in Sign in and Sign up page

### ISSUE THREAD

**Issue by kumarishalini6** [Girl-Code-It/Opportunity-Calendar-Frontend#218]
### **Describe the bug:**

There should be navbar in each and every page but navbar is not present in sign in and sign up page

**Comment by vaishali614** [comment]
Yes we need a navbar on that page. Since you've already been assigned an issue, I can't assign you this one until to complete that one.

**Comment by kumarishalini6** [comment]
Ok , I am working on that issue I will send PR by tomorrow then you can assign it

**Comment by ritik307** [comment]
@vaishali614 I would like to work on this issue plz assign.

**Comment by vaishali614** [comment]
@kumarishalini6 Since you've already been assigned an issue, I'm assigning this issue to @ritik307

**Comment by ritik307** [comment]
@vaishali614 thanks !

**Comment by kumarishalini6** [comment]
Wait I have send the PR of that issue I am waiting for this issue please don't you can assign him another issue that I have created

**Comment by kumarishalini6** [comment]
Ok sorry @ritik307 you can work on it
