### ISSUE TITLE
Inappropriate alignment of cards in tablet mode (768x1024) 

### ISSUE THREAD

**Issue by Samridhi-98** [Girl-Code-It/Opportunity-Calendar-Frontend#221]
# Expected Behavior:

Cards appear to be on the center rather than the left.

# Current Behavior:

What is the current behavior?
Cards appear to be on the left side rather than the center.

# Solution:
Will align the cards to the center in tablet mode.

# Screenshots (optional):
![image_2021_04_19T08_42_58_366Z](https://user-images.githubusercontent.com/54466041/115208067-d2556c00-a119-11eb-8096-ed8573665c37.png)

**Comment by Samridhi-98** [comment]
@vaishali614  I would like to work on this will you please assign it to me.

**Comment by vaishali614** [comment]
@Samridhi-98 You can go ahead with this but please make sure it's in center in all viewports (not only Tablet view).

**Comment by Samridhi-98** [comment]
> @Samridhi-98 You can go ahead with this but please make sure it's in center in all viewports (not only Tablet view).

Sure, will it in mind.
