### ISSUE TITLE
New Github Action

### ISSUE THREAD

**Issue by Inventor77** [Girl-Code-It/Opportunity-Calendar-Frontend#226]
### **Feature request**:

new github action for issue which have been not worked for more than 7days

### **Is your feature request related to a problem? Please describe. (optional)**:

No problem just a feature sugguestion

### **Describe the solution you'd like**:

Labeling stale to issue not been  worked for 7 days or more

### **Describe how this feature will be useful to our readers**:

A clear and concise description of how this feature will be useful for our other readers.

### **Additional context:**

Please Mentors @vaishali614  owerlook on this issue and assign level to it if it is worth changing

<hr/>

**Comment by vaishali614** [comment]
@Inventor77 Go ahead
