### ISSUE TITLE
Update API call to retrieve a list of opportunities

### ISSUE THREAD

**Issue by vaishali614** [Girl-Code-It/Opportunity-Calendar-Frontend#228]
Update the API in ViewOpportunity index.js file with https://opportunity-calendar.herokuapp.com/opportunity/?type=TYPE

where TYPE can be - HACKATHON, JOB, INTERNSHIP, SCHOLARSHIP, CONFERENCE, CODINGCOMPETITION

Follow this schema:
"data": [
    {
      "opportunityId": "3",
      "opportunityType": "SCHOLARSHIP",
      "opportunityLocation": "Chennai",
      "opportunityDescription": "The Novice Coders Scholarship Program",
      "opportunityEligibility": "Have no experience in coding",
      "opportunityRegistrationDeadline": "2021-03-22T12:04:05.779Z",
      "opportunityDate": "2021-03-22T12:04:05.779Z",
      "opportunityTitle": "Rohith M S R Scholarship",
      "opportunityURL": "www.rohithmsrscholarship.com"
    }
  ]

**Comment by akshitakanojia** [comment]
@vaishali614 can I work on this issue?

**Comment by vaishali614** [comment]
Sure. Go ahead.
