### ISSUE TITLE
Update API to create a new opportunity

### ISSUE THREAD

**Issue by vaishali614** [Girl-Code-It/Opportunity-Calendar-Frontend#229]
Update the API in all sections of PostOpportunity with: https://opportunity-calendar.herokuapp.com/opportunity

Example Schema:
{
  "opportunityTitle": "string",
  "opportunityType": "string",
  "opportunityOrganisation": "string",
  "opportunityLocation": "string",
  "opportunityDescription": "string",
  "opportunityEligibility": "string",
  "opportunityRegistrationDeadline": "2021-05-02",
  "opportunityDate": "2021-05-02",
  "opportunityURL": "string",
  "onlyForFemale": true,
  "organisationLogoURL": "string"
}

**Comment by Samridhi-98** [comment]
@vaishali614  I would like to work on it will you please assign it to me.

**Comment by wajeehamushtaq** [comment]
Hi @vaishali614 I am GSSOC'21 participant. I want to work on this issue. Can you please assign this to me?

**Comment by vaishali614** [comment]
@wajeehamushtaq Issues are assigned on FCFS basis, so I'm assigning this issue to @Samridhi-98
