### ISSUE TITLE
add search icon

### ISSUE THREAD

**Issue by ShrutiOmer** [Girl-Code-It/Opportunity-Calendar-Frontend#234]
### **Feature request**:

I want to add search icon in the search bar.

Please assign this issue to me.
### **Additional context:**

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by vaishali614** [comment]
@ShrutiOmer Go ahead

**Comment by vaishali614** [comment]
@ShrutiOmer any updates??
