### ISSUE TITLE
Implement Dynamic Search

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Opportunity-Calendar-Frontend#238]
### **Feature request**:

The search button is not functional as of now. Implement its logic to make it functional. 
Refer [this](https://levelup.gitconnected.com/building-a-simple-dynamic-search-bar-in-react-js-f1659d64dfae) or any other tutorial if you don't know how to do it.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by Manvityagi** [comment]
> Can I work on this issue under GSSoC'21? Kindly assign it to me.

You have an issue assigned in backend, You can be assigned this only after completing that one.

**Comment by akshitakanojia** [comment]
@Manvityagi  can I work on this issue?

**Comment by vaishali614** [comment]
@akshitakanojia Go ahead
