### ISSUE TITLE
Adding navbar options to footer.

### ISSUE THREAD

**Issue by RuchiGitHu** [Girl-Code-It/Opportunity-Calendar-Frontend#240]
### **Feature request**:

When we go to any "KNOW ABOUT" option like internship, Hackathons, Scholarships, etc. there is no option in website that can user to go back to home page of website. Without browser back option, user can't be able to back to home page of website. 

### **Is your feature request related to a problem? Please describe. (optional)**:

There should be option to user that after going to any page user can directly move to other page of website, at least for home page.

### **Describe the solution you'd like**:

I want to add Navbar option in footer of every "KNOW ABOUT" card page. So that after going through it, user can directly move back where they want without backing again and again using browser back.

### **Describe alternatives you've considered**:

Na

### **Describe how this feature will be useful to our readers**:

This will increase the good user experience.

### **Additional context:**
After clicking any card from here the requirement of this issue comes.
![image](https://user-images.githubusercontent.com/71754179/116820306-f8572380-ab91-11eb-844e-512adad0378e.png)

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by Manvityagi** [comment]
> ### **Feature request**:
> When we go to any "KNOW ABOUT" option like internship, Hackathons, Scholarships, etc. there is no option in website that can user to go back to home page of website. Without browser back option, user can't be able to back to home page of website.
> 
> ### **Is your feature request related to a problem? Please describe. (optional)**:
> There should be option to user that after going to any page user can directly move to other page of website, at least for home page.
> 
> ### **Describe the solution you'd like**:
> I want to add Navbar option in footer of every "KNOW ABOUT" card page. So that after going through it, user can directly move back where they want without backing again and again using browser back.
> 
> ### **Describe alternatives you've considered**:
> Na
> 
> ### **Describe how this feature will be useful to our readers**:
> This will increase the good user experience.
> 
> ### **Additional context:**
> After clicking any card from here the requirement of this issue comes.
> ![image](https://user-images.githubusercontent.com/71754179/116820306-f8572380-ab91-11eb-844e-512adad0378e.png)
> 
> **Note:**
> 
> * If you want to work on an issue, you should check if it has already been assigned to anyone.

Okay, Sounds good. Lets see your implementation :)
