### ISSUE TITLE
Add Social Icons to left of website

### ISSUE THREAD

**Issue by ShrutiOmer** [Girl-Code-It/Opportunity-Calendar-Frontend#242]
### **Feature request**:

I want to add social icons to left side of website, which on hovering scales out.

### **Describe the solution you'd like**:

I am a GSSoC'21 participant please assign this issue to me.
I have added this feature to a website and there its screenshot.
![image](https://user-images.githubusercontent.com/75009990/116860379-19b22100-ac1f-11eb-813d-0c74b930dbe0.png)

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by Manvityagi** [comment]
> ### **Feature request**:
> I want to add social icons to left side of website, which on hovering scales out.
> 
> ### **Is your feature request related to a problem? Please describe. (optional)**:
> ### **Describe the solution you'd like**:
> I am a GSSoC'21 participant please assign this issue to me.
> I have added this feature to a website and there its screenshot.
> ![image](https://user-images.githubusercontent.com/75009990/116860379-19b22100-ac1f-11eb-813d-0c74b930dbe0.png)
> 
> **Note:**
> 
> * If you want to work on an issue, you should check if it has already been assigned to anyone.

lOOKS GOOD @ShrutiOmer , Go ahead , Assigned to you :)

**Comment by vaishali614** [comment]
@ShrutiOmer You were already assigned an issue, but we assigned this issue to you simultaneously by mistake. Since your PR for previous issue is merged now, you can start working on this issue and your deadline will end after 2 days from today.
