### ISSUE TITLE
To add icons to navbar items

### ISSUE THREAD

**Issue by sreetu** [Girl-Code-It/Opportunity-Calendar-Frontend#244]
### **Feature request**:

To add icons to the navbar items.

### **Is your feature request related to a problem? Please describe. (optional)**:

A clear and concise description of what the problem is.

### **Describe the solution you'd like**:

I would add icons to the left of every navbar item.

### **Describe how this feature will be useful to our readers**:

It will contribute in enhancing the view.

### **Additional context:**

![Screenshot (790)](https://user-images.githubusercontent.com/72204621/117192463-618f9e80-adff-11eb-9468-f526ad69104c.png)

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by vaishali614** [comment]
@sreetu Thanks for opening an issue, however I like the navbar the way it is already.
@DeepanshiD @Manvityagi What are your opinions on this?

**Comment by DeepanshiD** [comment]
@sreetu I guess the current navbar is minimal and does the work perfectly, plus we have enough illustrations in the website and more addition of icons would make it feel a lil too much use of visuals. So we can let it be as it is right now.
CC: @vaishali614 @Manvityagi

**Comment by Manvityagi** [comment]
> @sreetu I guess the current navbar is minimal and does the work perfectly, plus we have enough illustrations in the website and more addition of icons would make it feel a lil too much use of visuals. So we can let it be as it is right now.
> CC: @vaishali614 @Manvityagi

Yeah I agree
