### ISSUE TITLE
Add smooth transition in meettheteam cards on hover

### ISSUE THREAD

**Issue by supzi-del** [Girl-Code-It/Opportunity-Calendar-Frontend#251]
- [x] I checked to make sure that this issue has not already been filed.

- [ ] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# Expected Behavior:

Expected Behavior:
Smooth css hover effect

# Current Behavior:

What is the current behavior?
On this page 👉 https://girlcodeit.com/meettheteam  when each card is hovered upon, the transition is a bit harsh/rough. 

# Solution:

Please describe what will you do to solve this issue or your approach to solve this issue.
A CSS code [transition: all 0.5s] can be added in order to have a smoother hover effect.

**Comment by vaishali614** [comment]
@supzi-del Thanks for pointing out this issue, but the page you're talking about is in a different repository: https://github.com/Girl-Code-It/Girl-Code-It-Website-Frontend. This repository is not a part of GSSoC, but if you still wanna work on this issue, please raise an issue on that repo. I'm closing this issue.

**Comment by supzi-del** [comment]
Okay! Is this the one? https://github.com/Girl-Code-It/Girl-Code-It-Website-Frontend

**Comment by vaishali614** [comment]
> Okay! Is this the one? https://github.com/Girl-Code-It/Girl-Code-It-Website-Frontend

Yes
