### ISSUE TITLE
Combine multiple Post Opportunity Forms into One form

### ISSUE THREAD

**Issue by vaishali614** [Girl-Code-It/Opportunity-Calendar-Frontend#254]
- [x] I checked to make sure that this issue has not already been filed.

- [x] I'm reporting the issue to the correct repository (for multi-repository projects) 

# Current Behavior:
Currently, there are separate forms for each opportunity.

# Solution:
Since all the forms are accepting same data, we can combine 6 forms into one.
There are a few differences:
1) Hackathons, Coding Competitions and Tech Conferences will have two date fields - Date of event, Deadline to apply
    whereas, Jobs, Internships, Scholarships will have only one field for date - Deadline to apply
2) Company Name will be only in Jobs, Internships

**Comment by AyushPradhan9** [comment]
Hey, I am interested in the issue. I have a solution to drop or add the fields as we select the opportunity type. Changes to be made:
1) The opportunity selecting dropdown menu will be moved to top to first be able to select opportunity type and the continue filling required detail in form. 
2) Removing all specific forms and making one generic form.

**Comment by vaishali614** [comment]
@AyushPradhan9 Great! You can go ahead with this.
