### ISSUE TITLE
Feedback form

### ISSUE THREAD

**Issue by kumarishalini6** [Girl-Code-It/Opportunity-Calendar-Frontend#255]
### **Feature request**:
There should be a feedback form , through feedback form  we came how much people like it how it is useful for the users and also let us know where we are lacking so that we can add that things in project .
I want to design this page under GSSOC'21 participants.

**Comment by rakshaa2000** [comment]
Hey, this has to have backend integration as well. I'll check up if this can be done.

**Comment by kumarishalini6** [comment]
Ok

**Comment by kumarishalini6** [comment]
I 'll also try to interigate

**Comment by rakshaa2000** [comment]
Hey, you can work on it. Just link the feedback form button to a Google form.

**Comment by kumarishalini6** [comment]
What type of Google form ?

**Comment by kumarishalini6** [comment]
Fir Google form we need a form

**Comment by rakshaa2000** [comment]
We will provide you with the link soon

**Comment by kumarishalini6** [comment]
ok

**Comment by kumarishalini6** [comment]
Hey! i have finished my work.

**Comment by kumarishalini6** [comment]
When you'll provide link

**Comment by vaishali614** [comment]
@kumarishalini6 Apologies for the delay. Please use this link for feedback form: https://forms.gle/jP3SEJgDcTPMiTGM7

**Comment by kumarishalini6** [comment]
That totally fine . Once I'll set the link then send PR.

**Comment by kumarishalini6** [comment]
I have send PR please have a look

**Comment by kumarishalini6** [comment]
Merged
