### ISSUE TITLE
Change style of opportunity form

### ISSUE THREAD

**Issue by kumarishalini6** [Girl-Code-It/Opportunity-Calendar-Frontend#262]
### **Feature request**:
I want to change style of form like:- 

![WhatsApp Image 2021-05-21 at 21 06 44](https://user-images.githubusercontent.com/69043944/119214258-e7ebe780-ba71-11eb-9035-25c010b99118.jpeg)

**Comment by kumarishalini6** [comment]
can i work on this issue under GSSoC'21.

**Comment by vaishali614** [comment]
@kumarishalini6 Which form are you talking about?

**Comment by kumarishalini6** [comment]
This form--
![Opportunity Calendar - Personal - Microsoft​ Edge 5_22_2021 08_07_53 PM](https://user-images.githubusercontent.com/69043944/119230387-6e331880-bac8-11eb-85db-61b245677951.png)

**Comment by vaishali614** [comment]
@kumarishalini6 There's already an issue for this #165 and someone is already working on it. So I'm closing this issue. Please find some other issue to work upon.
