### ISSUE TITLE
Adding a newsletter component

### ISSUE THREAD

**Issue by sandra9711** [Girl-Code-It/Opportunity-Calendar-Frontend#263]
### **Feature request**:

Adding a component for 'Signup for newsletter'

### **Describe the solution you'd like**:

I would like to design and implement a react component for newsletter subscription for this website

### **Describe how this feature will be useful to our readers**:

Users can subscribe to get opportunity alerts at the right time

<hr/>

**Comment by vaishali614** [comment]
@Manvityagi What are your opinions on this?

**Comment by Manvityagi** [comment]
> @Manvityagi What are your opinions on this?

Much needed feature. Thanks for pointing this out @sandra9711

**Comment by vaishali614** [comment]
@sandra9711 Please go ahead

**Comment by sandra9711** [comment]
![oc1](https://user-images.githubusercontent.com/66560251/119453967-997e6780-bd55-11eb-97d5-4206c194d25a.png)
![oc2](https://user-images.githubusercontent.com/66560251/119454037-af8c2800-bd55-11eb-8c65-3c8312dc1e01.png)
