### ISSUE TITLE
Font styling

### ISSUE THREAD

**Issue by chehak123** [Girl-Code-It/Opportunity-Calendar-Frontend#28]
I want to work on font styling in this website to make it look attractive. I am a participant in GSSOC 21. Can you please assign it to me.

**Comment by Surajbokde** [comment]
@chehak123  please provide some screenshots or videos.
so that we accept this issue under GSSoC'21

**Comment by nandini7637** [comment]
Hello I would like to contribute to it being a part of GSSOC, please assign me this issue
