### ISSUE TITLE
[ Enhacement ] Add animation in cards of known about

### ISSUE THREAD

**Issue by Surajbokde** [Girl-Code-It/Opportunity-Calendar-Frontend#29]
![image](https://user-images.githubusercontent.com/66197682/110196091-31ac3500-7e68-11eb-8350-9e4f481f9b7e.png)

1. add animation in cards-

animation maybe related to cards hover , change of image ,etc

2. modify the card.

add proper screenshots of your work

**Comment by vismitap** [comment]
Hey! I would like to work on this issue as a part of GSSOC'21!

**Comment by RituCs** [comment]
Hello, can I start working on this issue?If it is open please assign me.

**Comment by subhangi2731** [comment]
can you assign it to me?

**Comment by saumyaparikh** [comment]
I would like to contribute as a GSSOC'21 participate.

**Comment by mis-coder** [comment]
I would love to make those cards look alive (that's what animations do right). See if you could assign this issue to me.

**Comment by Surajbokde** [comment]
@vismitap  go ahead
