### ISSUE TITLE
Create Signup login Components

### ISSUE THREAD

**Issue by Surajbokde** [Girl-Code-It/Opportunity-Calendar-Frontend#30]
![image](https://user-images.githubusercontent.com/66197682/110196361-01fe2c80-7e6a-11eb-944d-06a810984b55.png)
create something like this.
best one will be selected
Add proper screenshots when it is done

**Comment by Sushi22** [comment]
I am a participant in GSSOC 21. I would like to work on this issue if assigned.

**Comment by vaishnavig20** [comment]
I am a participant in GSSOC 21. Can I be work on this issue

**Comment by Ankita297** [comment]
Can i work on this ?

**Comment by saumyaparikh** [comment]
I would like to contribute as a GSSOC'21 participate.

**Comment by Surajbokde** [comment]
@Sushi22  go ahead

**Comment by Sushi22** [comment]
okay thanks @Surajbokde

**Comment by Anuradha0501** [comment]
I am a participant in GSSOC 21. I would also like to work on this issue if assigned.

**Comment by Sushi22** [comment]
![Screenshot from 2021-03-10 20-05-47](https://user-images.githubusercontent.com/49645768/110645693-36604880-81dc-11eb-9f92-1f136288f513.png)
![Screenshot from 2021-03-10 20-14-37](https://user-images.githubusercontent.com/49645768/110646818-47f62000-81dd-11eb-8fc6-b7402bf8f9a4.png)

@Surajbokde I have created the Signup and login component. Please have a view so that I can improve if needed.

**Comment by Surajbokde** [comment]
@Sushi22  looks good to me .
@DeepanshiD please check

**Comment by DeepanshiD** [comment]
@Sushi22 @Surajbokde 
Keep enough space between title and input field. Now Email, password etc are dynamic text, once user starts typing it will vanish but this isn't a good flow. Rather keep a fixed title and input fields with proper spacing. 
In case you find an overflow, decrease size of text for titles. 
Sign up and Login button should be center aligned. 
Sign up using google must be below Sign up. 
"Already have an account, Login?" Shouldn't come as select field, rather as normal text. Place it just below form, followed by accepting TnC followed by Sign up button.

**Comment by Sushi22** [comment]
Okay, @DeepanshiD got it!
 I will do all these corrections. :)

Can you please send the link to the discord server for this project if we have?

**Comment by Surajbokde** [comment]
@Sushi22  you will added to discord soon

**Comment by vaishali614** [comment]
@Sushi22 There should be a "Login with Google" button too.

**Comment by Sushi22** [comment]
okay sure @vaishali614  I will add it :)

**Comment by Sushi22** [comment]
![Screenshot from 2021-03-11 00-50-08](https://user-images.githubusercontent.com/49645768/110684987-cc5b9980-8203-11eb-889c-80202b5b5e15.png)
![Screenshot from 2021-03-11 00-55-43](https://user-images.githubusercontent.com/49645768/110685669-894df600-8204-11eb-8dec-51995bc7a73d.png)

This looks good? Actually, the labels would not vanish when the user will fill the input fields, they will slide upwards, so now I think that the vanishing problem would not be there. Also, can we add a "Forgot Password " link too in the Login form? 
@vaishali614 @DeepanshiD @Surajbokde Please review.

**Comment by vaishali614** [comment]
@Sushi22 Looks good to me.

Some basic changes:
1. In Sign Up form, "Sign in with Google" --> "Sign Up with Google"
2. In Sign Up form, "Terms of Conditions" --> either "Terms of Use" or "Terms and Conditions"
3. In Login form, "Sign in with Google" --> "Login with Google" 
4. Yeah, we should have a "Forgot Password" link too.
5. I think the required "*" should be colored as #8b0000 or some other shade (optional - only if it looks good)

CC: @Surajbokde @DeepanshiD

**Comment by Sushi22** [comment]
![Screenshot from 2021-03-11 10-39-31](https://user-images.githubusercontent.com/49645768/110742445-63ecd680-825c-11eb-976d-69d47fe88089.png)
Should i put a logo upright there!? like this

**Comment by Sushi22** [comment]
I have made the required changes as well as added route for this component. 
![Screenshot from 2021-03-11 11-41-50](https://user-images.githubusercontent.com/49645768/110743922-db236a00-825e-11eb-938a-75e0c1ba6359.png)
![Screenshot from 2021-03-11 11-41-45](https://user-images.githubusercontent.com/49645768/110743932-e080b480-825e-11eb-9b76-794b1cee07aa.png)


please review once. @Surajbokde @vaishali614 @DeepanshiD

**Comment by DeepanshiD** [comment]
@Sushi22 The layout looks great! Forgot password has to be right aligned always.
It will look better if you increase button size of Sign up/Login to match Sign up with Google button size, that way it will look more consistent. 
Add some padding to the card, 16-24 px or something which is a multiple of 8.
The titles of input fields should be fixed, like the screenshot above.

**Comment by vaishali614** [comment]
@Sushi22 Please make the changes suggested by @DeepanshiD and send the PR. 
Also, the labels sliding upwards would look better than fixed labels. What do you think @Surajbokde ?

**Comment by Sushi22** [comment]
> @Sushi22 The layout looks great! Forgot password has to be right aligned always.
> It will look better if you increase button size of Sign up/Login to match Sign up with Google button size, that way it will look more consistent.
> Add some padding to the card, 16-24 px or something which is a multiple of 8.
> The titles of input fields should be fixed, like the screenshot above.

The titles would become fixed when user will start typing, they will slide upwards. Adding some more padding is actually disturbing the view in some devices, though I will for some way round to fix that.
other changes like button size I will make for sure. :)

**Comment by Sushi22** [comment]
> @Sushi22 Please make the changes suggested by @DeepanshiD and send the PR.
> Also, the labels sliding upwards would look better than fixed labels. What do you think @Surajbokde ?

yeah sure I will send the PR asap.

**Comment by Sushi22** [comment]
I have send the PR .Please review @DeepanshiD @vaishali614 @Surajbokde
