### ISSUE TITLE
Add validation  in post a job opportunity

### ISSUE THREAD

**Issue by Surajbokde** [Girl-Code-It/Opportunity-Calendar-Frontend#31]
![image](https://user-images.githubusercontent.com/66197682/110196534-2ad2f180-7e6b-11eb-95a2-a2b245a0ab0e.png)
Add validation in this

**Comment by AishwaryaKaranth** [comment]
Can I work on this as part of GSSOC'21 ?

**Comment by sahildotexe** [comment]
Hey !! I 'm a participant of GSSOC'21, can you assign this issue to me?

**Comment by Surajbokde** [comment]
@AishwaryaKaranth  go ahead

**Comment by abdus** [comment]
@AishwaryaKaranth Please respond if you are still working on this issue.

**Comment by AishwaryaKaranth** [comment]
> @AishwaryaKaranth Please respond if you are still working on this issue. 

Yes, I am. Will submit a PR shortly.

**Comment by AishwaryaKaranth** [comment]
Is there a deadline for solving this issue?

**Comment by Surajbokde** [comment]
@AishwaryaKaranth make pr today itself

**Comment by AishwaryaKaranth** [comment]
submitted PR #99

**Comment by AishwaryaKaranth** [comment]
submitted a new PR #105 
Resolved all conflicts.
