### ISSUE TITLE
Design view opportunity component for mobile and tab view

### ISSUE THREAD

**Issue by Surajbokde** [Girl-Code-It/Opportunity-Calendar-Frontend#32]
![image](https://user-images.githubusercontent.com/66197682/110196628-c95f5280-7e6b-11eb-9b65-a44a56ac8b45.png)
![image](https://user-images.githubusercontent.com/66197682/110196652-fe6ba500-7e6b-11eb-8870-2b5a54d6eb9d.png)
modify the circled part in both images

**Comment by saumyasrivastava08** [comment]
@Surajbokde Can I work on this.

**Comment by Surajbokde** [comment]
@saumyasrivastava08  go ahead

**Comment by saumyasrivastava08** [comment]
Sure

**Comment by saumyasrivastava08** [comment]
@Surajbokde i fixed the issue

**Comment by Surajbokde** [comment]
@saumyasrivastava08  we will review it soon
