### ISSUE TITLE
create about us component and add in home page

### ISSUE THREAD

**Issue by Surajbokde** [Girl-Code-It/Opportunity-Calendar-Frontend#33]
![image](https://user-images.githubusercontent.com/66197682/110197067-f3664400-7e6e-11eb-9644-2c5ab5092d38.png)
refer this image 
you can also refer https://girlcodeit.com/#about

**Comment by Meghag5** [comment]
I would like to work on this issue as a part of 2021 pls assign it to me

**Comment by VishalPatil18** [comment]
Hey, @Surajbokde I would like to work on this if you can assign it me. Thanks!

**Comment by nandini7637** [comment]
Hello I would like to contribute to it being a part of GSSOC, please assign it to me.

**Comment by saumyaparikh** [comment]
I would like to contribute as a GSSOC'21 participate.

**Comment by mis-coder** [comment]
Hi I would like to work on this issue!

**Comment by Surajbokde** [comment]
@Meghag5  go ahead

**Comment by VishalPatil18** [comment]
Hey, @Surajbokde I've finished making the about us component and also have added it to the home screen. Can I make a PR?
Thanks!

**Comment by Surajbokde** [comment]
@SpecTEviL  sure ,make pr

**Comment by VishalPatil18** [comment]
> @SpecTEviL sure ,make pr

Sure will do it ASAP after reading the guidelines.

**Comment by SpecTEviL** [comment]
Hey, @Surajbokde I've made a PR. You can review it. In case of any discrepancy do let me know.
Thanks!

**Comment by VishalPatil18** [comment]
Hey, @Surajbokde I've made a PR. You can review it. In case of any discrepancy do let me know.
Thanks!
