### ISSUE TITLE
create contact us component and add it to home page

### ISSUE THREAD

**Issue by Surajbokde** [Girl-Code-It/Opportunity-Calendar-Frontend#34]
![image](https://user-images.githubusercontent.com/66197682/110197178-ca927e80-7e6f-11eb-87be-0202c1972dfc.png)
we want name ,email ,message and button to send message

**Comment by khushboog12** [comment]
I would like to work on this issue as a part of GSSOC'21.

**Comment by VishalPatil18** [comment]
Hey, @Surajbokde I can try this. I appreciate it if you can assign this to me. Thanks!

**Comment by nandini7637** [comment]
Hello I would like to contribute to it being a part of GSSOC, please assign it to me

**Comment by sahildotexe** [comment]
Hey !! I 'm a participant of GSSOC'21, can you assign this issue to me?

**Comment by saumyasrivastava08** [comment]
I would like to contribute to this issue

**Comment by saumyaparikh** [comment]
I would like to contribute as a GSSOC'21 participate.

**Comment by Surajbokde** [comment]
@khushboog12    go ahead . Best one will be selected

**Comment by khushboog12** [comment]
> @khushboog12 go ahead . Best one will be selected

Thank you. Will work on it.
