### ISSUE TITLE
create FAQs component and add this to home page

### ISSUE THREAD

**Issue by Surajbokde** [Girl-Code-It/Opportunity-Calendar-Frontend#35]
![image](https://user-images.githubusercontent.com/66197682/110197595-95d3f680-7e72-11eb-813a-c565f786c83a.png)

**Comment by prachibansal2000** [comment]
I would like to work on this issue as a part of GSSOC'21

**Comment by promaroy** [comment]
Can I work on this as a part of GSSOC '21?

**Comment by subhangi2731** [comment]
can you please assign it to me?

**Comment by saumyasrivastava08** [comment]
Can I work on this? @Surajbokde

**Comment by saumyaparikh** [comment]
I would like to contribute as a GSSOC'21 participate.

**Comment by Surajbokde** [comment]
@prachibansal2000  go ahead
