### ISSUE TITLE
Make it Responsive

### ISSUE THREAD

**Issue by Vishv07** [Girl-Code-It/Opportunity-Calendar-Frontend#36]
The web app has some Responsiveness problems in the footer and some other areas.

**Comment by Surajbokde** [comment]
@Vishv07  please describe more about this issue

**Comment by saumyasrivastava08** [comment]
Can i work on this issue ? As we click on the opportunities folder then it is not properly responsive

**Comment by saumyaparikh** [comment]
I would like to contribute as a GSSOC'21 participate.

**Comment by EkjotKaur** [comment]
I would like to contribute on this issue (GSSOC'21).
Please assign me this issue @vishv07 @Surajbokde.

**Comment by Surajbokde** [comment]
@Vishv07 please describe more about this issue by tomorrow otherwise i will close this issue

**Comment by Vishv07** [comment]
Open this web app on your mobile or smaller screen and you will get to know. There are some divs and in the footer, there's inappropriate alignment.

**Comment by Surajbokde** [comment]
@Vishv07  go ahead

**Comment by Vishv07** [comment]
Hey @Surajbokde  Let @EkjotKaur Give it a shot

**Comment by Manvityagi** [comment]
@EkjotKaur Assigned to you - Level 1 issue - You have 2 days to complete it, If you are not able to complete it by then, it will be assigned to other contributors. 

Feel free to ping the mentors on the Discord server for any doubts.

**Comment by Surajbokde** [comment]
@EkjotKaur  this issue is promoted to level2  as you solved lots of issue
