### ISSUE TITLE
Adding Dark mode to the site.

### ISSUE THREAD

**Issue by Karthik-Nayak98** [Girl-Code-It/Opportunity-Calendar-Frontend#38]
I want to add a button that will toggle between Dark and Light mode.

**Comment by Karthik-Nayak98** [comment]
I want to contribute to this as a part of GSSOC 21.

**Comment by Manvityagi** [comment]
Seems like a good idea @Karthik-Nayak98. 
Go ahead!

**Comment by Karthik-Nayak98** [comment]
Yes sure. @Manvityagi

**Comment by 0Faiz0** [comment]
I would like to work on this issue as a Gssoc'21 participant

**Comment by Jassi10000-zz** [comment]
@Manvityagi  Mam , being a GSSOC'21 participant  I want to try my hands on this issue , please assign it to me , I will do my best to complete the task in required number of days

**Comment by Manvityagi** [comment]
@Karthik-Nayak98 The deadline for the issue has passed. 

I am assigning this issue to @0Faiz0.
If he doesn't make a PR within 3 days, it will be assigned to @Jassi10000.

You can start working on it @0Faiz0.

**Comment by Karthik-Nayak98** [comment]
Sure. @Manvityagi.

**Comment by Spring-dot** [comment]
@Manvityagi Is someone working on this issue? If not, Can I? I am GSSoC'21 participant.

**Comment by Manvityagi** [comment]
Let's wait for tonight, if @0Faiz0 or @Jassi10000 doesn't come to claim it, otherwise will assign it to you @Spring-dot

**Comment by mohammedjameel24** [comment]
Assign me

**Comment by Jassi10000-zz** [comment]
@Manvityagi mam is that issue still open and available?

**Comment by Manvityagi** [comment]
> @Manvityagi mam is that issue still open and available?

@0Faiz0 has made a PR for it, it's under review.

**Comment by Manvityagi** [comment]
@Karthik-Nayak98 @Jassi10000 @Spring-dot @mohammedjameel24 
This issue is Up-for-grabs, if anyone of you wants to work on it, comment here, will assign it to you. 

PS: Make sure you add a toggle button in the website which toggles dark and light modes.

**Comment by Spring-dot** [comment]
I want  to take this @Manvityagi

**Comment by mohammedjameel24** [comment]
Assign me

**Comment by mohammedjameel24** [comment]
> @Karthik-Nayak98 @Jassi10000 @Spring-dot @mohammedjameel24 
> This issue is Up-for-grabs, if anyone of you wants to work on it, comment here, will assign it to you. 
> 
> PS: Make sure you add a toggle button in the website which toggles dark and light modes.

Please assign me

**Comment by Manvityagi** [comment]
As per the FCFS rule, assigning to @Spring-dot

**Comment by Karthik-Nayak98** [comment]
I will open some other issue.

**Comment by mohammedjameel24** [comment]
Assign me

**Comment by Spring-dot** [comment]
@Manvityagi Ma'am I am getting errors while running localhost, I have arose this issue on discord also, but no answer yet. Please help.

**Comment by Jassi10000-zz** [comment]
@Manvityagi Mam please assign me the issue next , if its not been solved

**Comment by Manvityagi** [comment]
> @Manvityagi Ma'am I am getting errors while running localhost, I have arose this issue on discord also, but no answer yet. Please help.

Our mentor asked you to share the ss of the problem which you haven't sent yet afaik. 
Well, share the screenshot of your problem on the Discord channel. 
@vaishali614 will get in touch with you.

**Comment by Spring-dot** [comment]
okay, well I already send him ss in the direct message but I will share it again. Thanks for looking in my problem.

**Comment by Spring-dot** [comment]
@Manvityagi I have solved my error, I will be working on the issue, sorry for the delay, will update soon.

**Comment by sonalisonawane** [comment]
@Manvityagi Mam ,I would Like to work on this issue :) I want to contribute to this as a part of GSSOC 21.

**Comment by vaishali614** [comment]
> @Manvityagi I have solved my error, I will be working on the issue, sorry for the delay, will update soon.

Any updates?

**Comment by vaishali614** [comment]
> @Manvityagi Mam ,I would Like to work on this issue :) I want to contribute to this as a part of GSSOC 21.

@Spring-dot is already working on this issue. If she fails to create a PR by tomorrow, I'll assign it to you.

**Comment by Spring-dot** [comment]
> > @Manvityagi I have solved my error, I will be working on the issue, sorry for the delay, will update soon.
> 
> Any updates?

yes, I will update you by tomorrow, got college exam so I am lagging in my work.

**Comment by vaishali614** [comment]
> > > @Manvityagi I have solved my error, I will be working on the issue, sorry for the delay, will update soon.
> > 
> > 
> > Any updates?
> 
> yes, I will update you by tomorrow, got college exam so I am lagging in my work.

Any updates @Spring-dot?

**Comment by Spring-dot** [comment]
> > > > @Manvityagi I have solved my error, I will be working on the issue, sorry for the delay, will update soon.
> > > 
> > > 
> > > Any updates?
> > 
> > 
> > yes, I will update you by tomorrow, got college exam so I am lagging in my work.
> 
> Any updates @Spring-dot?

I am caught by fever and cold, assign to someone else, I can't work long on laptop. sorry :(

**Comment by vaishali614** [comment]
> > > > > @Manvityagi I have solved my error, I will be working on the issue, sorry for the delay, will update soon.
> > > > 
> > > > 
> > > > Any updates?
> > > 
> > > 
> > > yes, I will update you by tomorrow, got college exam so I am lagging in my work.
> > 
> > 
> > Any updates @Spring-dot?
> 
> I am caught by fever and cold, assign to someone else, I can't work long on laptop. sorry :(

Sorry to hear that. Please take care. 
You can take up some other issue as soon as you get well. Looking forward to more contributions from you.

**Comment by shriya030** [comment]
@vaishali614 I can try this :) Can you assign this to me?

**Comment by vaishali614** [comment]
> @vaishali614 I can try this :) Can you assign this to me?

Sure. Go ahead.

**Comment by Jassi10000-zz** [comment]
> @Manvityagi Mam , being a GSSOC'21 participant I want to try my hands on this issue , please assign it to me , I will do my best to complete the task in required number of days

@vaishali614 , @Manvityagi   Mam I commented a lot before than other participants , then also I have not been assigned this

**Comment by vaishali614** [comment]
> > @Manvityagi Mam , being a GSSOC'21 participant I want to try my hands on this issue , please assign it to me , I will do my best to complete the task in required number of days
> 
> @vaishali614 , @Manvityagi Mam I commented a lot before than other participants , then also I have not been assigned this

Apologies. Missed your comments among numerous comments. Assigning this issue to you now.
@shriya030 if @Jassi10000 fails to complete it within 5 days, it'll be assigned to you.

**Comment by mohammedjameel24** [comment]
Assign me @vaishali614

**Comment by vaishali614** [comment]
> Assign me @vaishali614

@Jassi10000 has been assigned on FCFS basis.

**Comment by Jassi10000-zz** [comment]
Thanks mam @vaishali614

**Comment by Manvityagi** [comment]
@Jassi10000 What's the status of the PR for this issue?

**Comment by Jassi10000-zz** [comment]
@Manvityagi Mam will send it soon , actually was busy due to an exam that's why

**Comment by vaishali614** [comment]
@Jassi10000 Would like to receive a PR on this by tomorrow. You can't stay assigned to one issue this long as per rules.

**Comment by mohammedjameel24** [comment]
Assign me

**Comment by Jassi10000-zz** [comment]
@vaishali614 Mam I would have submiitted the PR , but am not able to access even the localhost 

![doutbt1](https://user-images.githubusercontent.com/64856348/114133277-6c036900-9923-11eb-9735-ff798394fb39.PNG)

Am again and again encountering this error


After I do "npm start" this error appears   after  the line  " react - scripts ......."

**Comment by vaishali614** [comment]
Try following this: https://stackoverflow.com/questions/66064706/react-module-parse-failed-unexpected-token-148

**Comment by Jassi10000-zz** [comment]
> Try following this: https://stackoverflow.com/questions/66064706/react-module-parse-failed-unexpected-token-148

Am still getting the same error even after following the same steps

**Comment by Jassi10000-zz** [comment]
> > Try following this: https://stackoverflow.com/questions/66064706/react-module-parse-failed-unexpected-token-148
> 
> Am still getting the same error even after following the same steps

@vaishali614 Mam can you please  help

**Comment by mohammedjameel24** [comment]
assign me @vaishali614

**Comment by Jassi10000-zz** [comment]
Mam  @vaishali614  , you can assign to @mohammedjameel24  as am facing a lot of issues while starting the application as well seeing my changes made to the application

**Comment by mohammedjameel24** [comment]
am not able to push code to develop branch which came default after cloning into the repo

error
`$ git push origin develop`
`remote: Permission to Girl-Code-It/Opportunity-Calendar-Frontend.git denied to mohammedjameel24.
fatal: unable to access 'https://github.com/Girl-Code-It/Opportunity-Calendar-Frontend.git/': The requested URL returned error: 403 `

@vaishali614

**Comment by Manvityagi** [comment]
Seems like you didn't fork @mohammedjameel24.

Follow the steps in contributing.md

**Comment by mohammedjameel24** [comment]
> Seems like you didn't fork @mohammedjameel24.
> 
> Follow the steps in contributing.md

Ooooooo noob mistake

**Comment by mohammedjameel24** [comment]
pull request #207
