### ISSUE TITLE
fix NavBar Button Error!

### ISSUE THREAD

**Issue by bhubesh757** [Girl-Code-It/Opportunity-Calendar-Frontend#41]
After pressing the button its not scrolling to the particular content/ page

**Comment by abdus** [comment]
Nice catch. Let me know if you want to work on this, and I will assign this to you.

**Comment by vismitap** [comment]
May I work on this issue as a part of GSSOC'21?

**Comment by rutuja2229** [comment]
I want to try for this, participant of GSSoC 2021, can I work on this issue?

**Comment by Manvityagi** [comment]
@abdus , Are we waiting for @bhubesh757 ?

**Comment by abdus** [comment]
@Manvityagi, since @bhubesh757 neither expressed their willingness to work on this issue while creating it nor responded, I would go ahead and assign @vismitap.

I am sorry I can't assign this issue to you at the moment, @rutuja2229. Issues are assigned on a First Come First Serve basis.

**Comment by bhubesh757** [comment]
I will assign this issue , actually i was in a class @abdus

**Comment by abdus** [comment]
@bhubesh757 Please find another [issue from here](https://github.com/Girl-Code-It/Opportunity-Calendar-Frontend/issues?q=is%3Aissue+is%3Aopen+label%3Aup-for-grabs)

**Comment by bhubesh757** [comment]
@abdus  Just now i Solved , I completed
