### ISSUE TITLE
Adding hover effects on buttons

### ISSUE THREAD

**Issue by kanak22** [Girl-Code-It/Opportunity-Calendar-Frontend#42]
I saw that the buttons on the site don't have a hover effect. Can I work on this and contribute to the project as a part of GSSOC'21. Kindly assign it to me.

**Comment by abdus** [comment]
Sure. Feel free to contact us through discord if you get stuck.

**Comment by kanak22** [comment]
Sure 😊

**Comment by riyakansal2901** [comment]
Can I work on this ? I started learning CSS few months back and found it to be really fun . W ould love to work on this .
