### ISSUE TITLE
Changing the "No Opportunities " to "Loading Opportunities if any" on all components

### ISSUE THREAD

**Issue by mohitms007** [Girl-Code-It/Opportunity-Calendar-Frontend#44]
This usually creates a dilemma of no opportunities so users generally close the website immediately, we can make this change so that users stay and wait for the results to appear

**Comment by mohitms007** [comment]
Can I be assigned this issue

**Comment by saumyasrivastava08** [comment]
@mohitms007  We can add preloader to

**Comment by mohitms007** [comment]
Yes we definitely can!

**Comment by abdus** [comment]
@mohitms007 finish assigned issues first.

**Comment by promaroy** [comment]
Can I work on this issue as a part of GSSOC '21?

**Comment by vaishali614** [comment]
@promaroy go ahead

**Comment by promaroy** [comment]
Please review my PR.
https://github.com/Girl-Code-It/Opportunity-Calendar-Frontend/pull/68
