### ISSUE TITLE
Adding Unit Tests to the Project

### ISSUE THREAD

**Issue by mohitms007** [Girl-Code-It/Opportunity-Calendar-Frontend#47]
We can add unit tests to the project to make it more reliable and better as tests are one of the most important things in a project.
Can I be assigned to this issue???

**Comment by Vishv07** [comment]
What are you planning to add Cypress or jest?

**Comment by mohitms007** [comment]
Jest

**Comment by mohitms007** [comment]
Wanted to ask should I keep the tests in btween folders or create a seperate folder for all the tests?

**Comment by Vishv07** [comment]
Create a separate folder for tests. It would be better

**Comment by mohitms007** [comment]
Yeah doing the same!

**Comment by mohitms007** [comment]
I have made a pull request and the details too have been added. Was facing issues as PL produced 5 checks errors but updated the package.json and now pull request is ready to be merged.
