### ISSUE TITLE
unnecessary White Space to right side of the cards So we can make this card full width in mobile view

### ISSUE THREAD

**Issue by dsnehasish74** [Girl-Code-It/Opportunity-Calendar-Frontend#56]
![Screenshot (541)](https://user-images.githubusercontent.com/58779604/110646071-89d29680-81dc-11eb-8b9d-26d39a548a45.png)

Can you Please assign this issue to me. I want to contribute as part of Gssoc21

**Comment by Surajbokde** [comment]
@dsnehasish74  go ahead

**Comment by dsnehasish74** [comment]
Thank you

**Comment by Surajbokde** [comment]
@dsnehasish74  sorry to say , but someone solved this issue as sub-issue so i am closing this issue.
you can look for another issue
