### ISSUE TITLE
Increasing the font size and adding some spacing in deadline in the opportunity cards in mobile view

### ISSUE THREAD

**Issue by kartikpuri99** [Girl-Code-It/Opportunity-Calendar-Frontend#57]
![image](https://user-images.githubusercontent.com/52126579/110648062-66a8e680-81de-11eb-8bd5-4ebd8c2a840b.png)
Please assign this issue to me as a part of GSSOC'21

**Comment by saumyasrivastava08** [comment]
I am working on this kindly check issue #32
