### ISSUE TITLE
Design Search Component on the Home page

### ISSUE THREAD

**Issue by nandini2110** [Girl-Code-It/Opportunity-Calendar-Frontend#59]
I would like to make changes to this search bar styling
<img width="252" alt="12" src="https://user-images.githubusercontent.com/51056716/110650680-c1dbd880-81e0-11eb-8a54-1fbc94c62c20.PNG">

In an attempt to improvise on the styling of the search bar and add effects to it

I would like to work on this issue as a part of GSSOC'21

**Comment by vaishali614** [comment]
@nandini2110 This issue has been solved as a sub-issue of some other issue. Please look on other issues.
