### ISSUE TITLE
fix Post oppurtunity  in  Explore ! 

### ISSUE THREAD

**Issue by bhubesh757** [Girl-Code-It/Opportunity-Calendar-Frontend#63]
**Issue**
If We press the Button in Post oppurtunity from this link https://happy-shockley-488e36.netlify.app/viewopportunity/hackathon =>  it redirects to the page of https://happy-shockley-488e36.netlify.app/postopportunity/hackathon  the issue is Only Footer is Available 
The Header and  Form is not Visible and this issue is also suits for oppurtunities abd The Rest of the options are fine
@abdus  If Anybody is Willing To Contribute to this , or Otherwise i will Fix the issue 

https://user-images.githubusercontent.com/55022929/110666553-72e96f80-81ef-11eb-8944-120bde38da8f.mp4

**Comment by dsnehasish74** [comment]
I want to work on this as part of GSSOC21 can you assign this to me

**Comment by abdus** [comment]
@bhubesh757 sure, you can start working on it.
