### ISSUE TITLE
Add Some Css and contact form in it.

### ISSUE THREAD

**Issue by saumyasrivastava08** [Girl-Code-It/Opportunity-Calendar-Frontend#67]
Can I work on this .

**Comment by abdus** [comment]
Can you explain what kind of changes you will be making?

**Comment by saumyasrivastava08** [comment]
Will make one row and little section of contact form.

**Comment by healer9** [comment]
@abdus Instead of sending contact-us form data to the backend and then storing it for future use.

Can we use [Formspree](https://formspree.io/) a third-party app to handle these types of form submissions and sending the data to the email we provide (e.g email of Admin). Because storing the contact-us form data to the database is irrelevant for us.

By doing this we can use the database only for storing the data of login and sign-in form. 🙂

**Comment by healer9** [comment]
If you find this helpful and relevant then assign handling of contact-form data to me I will create all the front-end and also handle the Formspree API for this task.

**Comment by abdus** [comment]
@healer9 I will discuss this with the project admin and let you know. In other projects under Girl-Code-It, we use formspree. So, we will probably be using formspree for this project as well.


cc: @Manvityagi

**Comment by Manvityagi** [comment]
Yes, we can go with formspree for time being, will see later if any blockers. 

Cc: @abdus

**Comment by saumyasrivastava08** [comment]
@Manvityagi Rather than formspree we can use react-redux system that will not show that we have use any third part application.

**Comment by healer9** [comment]
# @abdus assign this issue to me and also provide me the fields you want to be in the contact form.

### ` Provide me the email of the project admin(where you want to send the contact form data) and the authentication token also i.e, generated by Fromspree.`

**Comment by healer9** [comment]
@abdus assigns this issue to me so that I can add this formspree feature to the app. 
Do I have to create a new issue for this feature?

And provide me the email address where you want to send the contact-us form data after submission, with the auth token provided by the Formspree.

**Comment by abdus** [comment]
@healer9 sure, go ahead and get this task done.

@saumyasrivastava08 `react-redux` and Fromspree, both are different. I don't think we would require redux for this project. 
... assigned you a different issue.
