### ISSUE TITLE
Meet the team

### ISSUE THREAD

**Issue by Sapna2001** [Girl-Code-It/Opportunity-Calendar-Frontend#81]
I would like to work on the meet the team page. Currently, only the footer is visible on that page, please let me know the requirements for it.

![Screenshot from 2021-03-11 19-12-34](https://user-images.githubusercontent.com/56690856/110796381-e3e76080-829d-11eb-8684-28e2851e9367.png)

**Comment by abdus** [comment]
We already have a [`Meet the Team`](https://girlcodeit.com/meettheteam) on the main website. @Manvityagi do we need a separate `Meet the Team` page for the Opp. Calendar website?

**Comment by abdus** [comment]
Closing. Reopen if you feel like this issue should be addressed.

**Comment by Manvityagi** [comment]
> We already have a [`Meet the Team`](https://girlcodeit.com/meettheteam) on the main website. @Manvityagi do we need a separate `Meet the Team` page for the Opp. Calendar website?

Yeah, it's not needed here @abdus @Sapna2001
