### ISSUE TITLE
[GSSOC21] Adding a side scroll bar which allows scrolling to a specific section of the home page

### ISSUE THREAD

**Issue by Fangston0** [Girl-Code-It/Opportunity-Calendar-Frontend#82]
I plan to add a simple side scroll bar, one with clickable icons/circles that will take you to the different sections of the home page. It can be used to quickly navigate to the important information.

**Comment by zaverisanya** [comment]
I am a participant at GSSoC'21 , please can you assign this issue to me?

**Comment by abdus** [comment]
@Fangston0 we have a navbar for that.
