### ISSUE TITLE
Design a better logo(Girl Code it) and add it in title and footer section.

### ISSUE THREAD

**Issue by janvi01** [Girl-Code-It/Opportunity-Calendar-Frontend#84]

**Comment by janvi01** [comment]
I would like to work.

**Comment by abdus** [comment]
cc: @Manvityagi

**Comment by Spring-dot** [comment]
@Manvityagi Is someone working on this issue?

**Comment by Manvityagi** [comment]
@janvi01 wanna work on this? 

PS: @Spring-dot, If @janvi01 doesn't reply by tonight, I will assign it to you.

**Comment by janvi01** [comment]
Yes definately @Manvityagi

**Comment by Manvityagi** [comment]
@janvi01 Added the respective tags and assigned to you. 
Feel free to discuss any ideas/doubts while implementing the solution. 
@DeepanshiD is mentoring the Design part. Feel free to contact her as well.

**Comment by janvi01** [comment]
Thankyou

**Comment by janvi01** [comment]
@Manvityagi I have made a new logo, please can you review it.
Where should I post the logo, here or in discord channel?

**Comment by Manvityagi** [comment]
Post it on Discord, everyone will be able to see.

**Comment by vaishali614** [comment]
> @Manvityagi I have made a new logo, please can you review it.
> Where should I post the logo, here or in discord channel?

Have you shared the logo yet?

**Comment by janvi01** [comment]
Yes I have shared with Deepanshi mam.

**Comment by janvi01** [comment]
@DeepanshiD I have shared logo, Please check
