### ISSUE TITLE
To style The cards

### ISSUE THREAD

**Issue by saumyasrivastava08** [Girl-Code-It/Opportunity-Calendar-Frontend#85]
As @vaishali614 said me to change the styles of cards like this . Can I start ?
![sssss](https://user-images.githubusercontent.com/57553757/110817735-95908c80-82b2-11eb-9fbd-a6c26d7f8715.png)

**Comment by Hritikkumar** [comment]
Hi @abdus, I want to contribute to this issue. Please assign this issue to me.

**Comment by abdus** [comment]
@Hritikkumar It's already assigned to @saumyasrivastava08.

**Comment by saumyasrivastava08** [comment]
Yes, i am working on it

**Comment by saumyasrivastava08** [comment]
![Screenshot (57)](https://user-images.githubusercontent.com/57553757/110936358-c88c5c00-8356-11eb-8596-c0a23ab3e9ad.png)
![Screenshot (58)](https://user-images.githubusercontent.com/57553757/110936367-c9bd8900-8356-11eb-80f2-00676ab04d07.png)


@abdus @vaishali614 is it okay

**Comment by saumyasrivastava08** [comment]
@abdus done

**Comment by vaishali614** [comment]
@saumyasrivastava08 Looks good. Few basic changes -

1. Increase the card width.
2. Keep the image square-shaped.
3. Increase font-size of Opportunity Title.
4. Shift the "Apply" button to right (I think it'll look better).
5. In mobile view, maybe you can remove the image.

**Comment by vaishali614** [comment]
@saumyasrivastava08 There are few issues with responsiveness.

1. Mobile View
![Screenshot (228)](https://user-images.githubusercontent.com/32364768/110943032-b7e0e380-8360-11eb-8052-12288321bbc0.png)

2. Increase card width. 
![Screenshot (230)](https://user-images.githubusercontent.com/32364768/110943084-c9c28680-8360-11eb-937a-27087751bbdc.png)

3. Cards should be in middle.
![Screenshot (231)](https://user-images.githubusercontent.com/32364768/110943161-e5c62800-8360-11eb-8b92-fbb09a2d2846.png)

**Comment by saumyasrivastava08** [comment]
![Screenshot (58)](https://user-images.githubusercontent.com/57553757/110946505-f24c7f80-8364-11eb-853a-0ffa98d2bbc8.png)
![Screenshot (59)](https://user-images.githubusercontent.com/57553757/110946510-f4164300-8364-11eb-9356-799c649deef7.png)
![Screenshot (60)](https://user-images.githubusercontent.com/57553757/110946515-f5477000-8364-11eb-997d-4d8410b3b836.png)
![Screenshot (61)](https://user-images.githubusercontent.com/57553757/110946518-f6789d00-8364-11eb-8f1a-08c844105817.png)
![Screenshot (62)](https://user-images.githubusercontent.com/57553757/110946522-f7113380-8364-11eb-861c-f57360e8ac26.png)


@vaishali614

**Comment by saumyasrivastava08** [comment]
> @saumyasrivastava08 Looks good. Few basic changes -
> 
> 1. Increase the card width.
> 2. Keep the image square-shaped.
> 3. Increase font-size of Opportunity Title.
> 4. Shift the "Apply" button to right (I think it'll look better).
> 5. In mobile view, maybe you can remove the image.

Done these also just check and tell if some changes needed
