### ISSUE TITLE
Add Filter ,Recent Search !🚀

### ISSUE THREAD

**Issue by bhubesh757** [Girl-Code-It/Opportunity-Calendar-Frontend#87]
@abdus By Adding Filter in the explore page so they find their particular content Easily . and Also the Recent Search  under the search button so ,it might look page good , i will add the ui

**Comment by bhubesh757** [comment]
@abdus  look into this i will send the ui design

**Comment by abdus** [comment]
what kind of filters are you talking about? can you explain it a bit?

**Comment by bhubesh757** [comment]
For example if the user wants to search the job , for their qualification so they can add their qualification to the filter so  it will show only the jobs which is suits for his/her qual , this also suits to all the options

**Comment by abdus** [comment]
@Surajbokde @vaishali614

**Comment by Manvityagi** [comment]
@bhubesh757 Please specify in a little more detail. What exactly are the filters. Implementing the same would also need a some modifications in the API.

**Comment by vaishali614** [comment]
@bhubesh757 Please elaborate your idea so that we can plan things better or else, I'll close this issue.

**Comment by bhubesh757** [comment]
> @bhubesh757 Please elaborate your idea so that we can plan things better or else, I'll close this issue.

Close the issue
