### ISSUE TITLE
[GSSoC'21] To make the 'install' section of README file comprehensible.

### ISSUE THREAD

**Issue by zaverisanya** [Girl-Code-It/Opportunity-Calendar-Frontend#88]
I am a newbie to Open Source Community. After forking and cloning the project locally I personally faced issues in running the project locally. I believe many others might also face the same issue. Therefore I want to make changes to the existing 'install' section of README file `Opportunity-Calendar-Frontend/README.md`  to make it detailed and unambiguous. 

@abdus @Manvityagi Kindly let me know whether I can work on this issue or not?

**Comment by abdus** [comment]
Sure. Go ahead.
