### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [Girl-Code-It/Opportunity-Calendar-Frontend#91]
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by abdus** [comment]
Can you explain how are you planning to implement the contributors' list automatically?

**Comment by aj3011** [comment]
I am a GSSoC's 21 participant and I would like to work on this issue. I would like to use the link of the page that shows the history of contributors to automatically update the list of contributors in the readme file

**Comment by rohan-kulkarni-25** [comment]
> Can you explain how are you planning to implement the contributors' list automatically?

I will add a img tag which will keep this section updating
