### ISSUE TITLE
Modify Page of Post Job Opportunity

### ISSUE THREAD

**Issue by saumyasrivastava08** [Girl-Code-It/Opportunity-Calendar-Frontend#92]
![Screenshot (63)](https://user-images.githubusercontent.com/57553757/110948935-fcbc4880-8367-11eb-9a6f-6ffa13049d4b.png)

###Following changes to be made
1.) Box around the form that will look attractive
2.) Shift search bar corner / add login option

**Comment by saumyasrivastava08** [comment]
@abdus can i work on this?

**Comment by rutuja2229** [comment]
@saumyasrivastava08 @abdus  Can I work on this issue please, I am GSSoC2021 participant.

**Comment by nandita658** [comment]
Can i work on this issue?

**Comment by abdus** [comment]
cc: @vaishali614

**Comment by DeepanshiD** [comment]
@saumyasrivastava08 @rutuja2229 We appreciate your interest, but we assign tasks on First come first serve bases. So @saumyasrivastava08 you can take up the task. And @rutuja2229 how about, going through some other task?

**Comment by DeepanshiD** [comment]
@saumyasrivastava08 There's a small addition on top right there will be a search bar and a login/sign up button beside it.  In case you can't figure it out, ping me I will share pen paper design

**Comment by saumyasrivastava08** [comment]
> @saumyasrivastava08 There's a small addition on top right there will be a search bar and a login/sign up button beside it. In case you can't figure it out, ping me I will share pen paper design

yeah sure make it attach it here and i will start working on this and label this as gssoc. 

Thanks

**Comment by DeepanshiD** [comment]
@saumyasrivastava08 
![WhatsApp Image 2021-03-12 at 21 51 21](https://user-images.githubusercontent.com/41962533/110968166-36e41500-837d-11eb-9761-64956c110471.jpeg)

**Comment by saumyasrivastava08** [comment]
> @saumyasrivastava08
> ![WhatsApp Image 2021-03-12 at 21 51 21](https://user-images.githubusercontent.com/41962533/110968166-36e41500-837d-11eb-9761-64956c110471.jpeg)

okay done 
add gssoc label

**Comment by saumyasrivastava08** [comment]
and where is our channel on discord there are channels for every community but where is ours @Manvityagi

**Comment by saumyasrivastava08** [comment]
please assign me

**Comment by Manvityagi** [comment]
> and where is our channel on discord there are channels for every community but where is ours @Manvityagi

#opportunity-calendar-frontend
#opportunity-calendar-backend
