### ISSUE TITLE
Change stateless class components to functional components

### ISSUE THREAD

**Issue by girkarkshitij** [Girl-Code-It/Opportunity-Calendar-Frontend#95]
There are some class components in the project which do not have any state, we should change them into functional components.

![Screenshot (181)](https://user-images.githubusercontent.com/43858028/111022527-32f5d880-83f9-11eb-97da-4711e818330d.png)

**Comment by girkarkshitij** [comment]
Please assign this issue to me.

**Comment by abdus** [comment]
Can you please explain why we should change them to functional components?

**Comment by girkarkshitij** [comment]
I know that there is no significant performance differences between them but :

1. Functional component are much easier to read and test because they are plain JavaScript functions without state or lifecycle hooks
2. We will end up with less code

**Comment by abdus** [comment]
Okay. Sure, go ahead.
