### ISSUE TITLE
Add Icons in the Contact Us Section

### ISSUE THREAD

**Issue by prachibansal2000** [Girl-Code-It/Opportunity-Calendar-Frontend#96]
![image](https://user-images.githubusercontent.com/56162563/111022831-54f05a80-83fb-11eb-9cbb-9fb5db8d6573.png)

I would like to work on this issue as a part of GSSOC'21

**Comment by abdus** [comment]
What kind of icons are you talking about? A little information would help...

**Comment by prachibansal2000** [comment]
> What kind of icons are you talking about? A little information would help...

![image](https://user-images.githubusercontent.com/56162563/111038588-d671d800-844f-11eb-8785-951b7881c7b3.png)
 As shown in the image

**Comment by abdus** [comment]
@Surajbokde @vaishali614

**Comment by Surajbokde** [comment]
@prachibansal2000  adding icons will looks good but we want blue icons

https://surajbokde.github.io/Nature_Beauty/contact.html
Just have a look on get in touch

**Comment by prachibansal2000** [comment]
> @prachibansal2000 adding icons will looks good but we want blue icons
> 
> https://surajbokde.github.io/Nature_Beauty/contact.html
> Just have a look on get in touch

Sure i will add blue icons

**Comment by Cgoyal48** [comment]
> @prachibansal2000 adding icons will looks good but we want blue icons
> 
> https://surajbokde.github.io/Nature_Beauty/contact.html
> Just have a look on get in touch

Sir, I would like to work on this issue. Can you please assign this to me?
I am a GSSOC'21 participant.
